// Generated by deckwright — this script produces builder.pptx
// Edit THIS FILE, not the .pptx. Changes to builder.pptx will be
// overwritten the next time this script runs.
//
// Run: node builder.js

const pptxgen = require("pptxgenjs");
const fs = require("fs");
const path = require("path");

// ============================================================
// DESIGN SYSTEM (identical to main ai-best-practices deck)
// ============================================================
const D = {
  bg: "0A2540", lightBg: "FFFFFF", glow: "635BFF",
  white: "FFFFFF", text: "EDEDED", muted: "8B95A5", darkText: "1A1F36",
  accent: "635BFF", wrong: "FF6B8A", wrongBg: "FEE2E8", right: "09825D", rightBg: "DCFCE7",
  h: "Georgia", b: "Verdana",
};

// ============================================================
// UTILITIES
// ============================================================
function darkSlide(pres) {
  const s = pres.addSlide();
  s.background = { color: D.bg };
  s.addShape(pres.shapes.OVAL, {
    x: 5, y: 2.5, w: 8, h: 6,
    fill: { color: D.accent, transparency: 96 }
  });
  return s;
}

function breatherSlide(pres, text, notes) {
  const s = darkSlide(pres);
  s.addText(text, {
    x: 1.5, y: 2.0, w: 7, h: 1.6,
    fontFace: D.h, fontSize: 28, color: D.accent, italic: true,
    align: "center", margin: 0, valign: "middle"
  });
  if (notes) s.addNotes(notes);
  return s;
}

function sectionDivider(pres, d) {
  const s = darkSlide(pres);
  s.addText(d.title, {
    x: 0.5, y: 1.6, w: 9, h: 1.2,
    fontFace: D.h, fontSize: 54, color: D.white, bold: true, align: "center", margin: 0
  });
  if (d.subtitle) {
    s.addText(d.subtitle, {
      x: 1.0, y: 2.9, w: 8, h: 0.6,
      fontFace: D.b, fontSize: 28, color: D.accent, italic: true, align: "center", margin: 0
    });
  }
  s.addNotes(d.notes || "");
  return s;
}

function bigNum(pres, num, sub, opts = {}) {
  const s = darkSlide(pres);
  const numColor = opts.color || D.white;
  s.addText(num, {
    x: 0.5, y: 1.0, w: 9, h: 2.5,
    fontFace: D.h, fontSize: opts.numSize || 120,
    color: numColor, bold: true, align: "center", margin: 0, valign: "bottom"
  });
  s.addText(sub, {
    x: 1.5, y: 3.6, w: 7, h: 0.8,
    fontFace: D.b, fontSize: 28,
    color: D.muted, align: "center", margin: 0, valign: "top"
  });
  if (opts.source) {
    if (typeof opts.source === "string") {
      s.addText(opts.source, {
        x: 0.5, y: 5.0, w: 9, h: 0.4,
        fontFace: D.b, fontSize: 11, color: D.muted, align: "right", margin: 0, valign: "bottom"
      });
    } else {
      const parts = [];
      opts.source.forEach((src, i) => {
        if (i > 0) parts.push({ text: ", ", options: { fontFace: D.b, fontSize: 11, color: D.muted } });
        const p = { text: src.text, options: { fontFace: D.b, fontSize: 11, color: D.muted } };
        if (src.url) p.options.hyperlink = { url: src.url };
        parts.push(p);
      });
      s.addText(parts, {
        x: 0.5, y: 5.0, w: 9, h: 0.4,
        align: "right", margin: 0, valign: "bottom"
      });
    }
  }
  if (opts.notes) s.addNotes(opts.notes);
  return s;
}

function hero(pres, main, opts = {}) {
  const s = darkSlide(pres);
  s.addText(main, {
    x: 1.0, y: 1.2, w: 8, h: 2.8,
    fontFace: opts.font || D.h, fontSize: opts.size || 44,
    color: opts.color || D.white, bold: true,
    align: "center", margin: 0, valign: "middle"
  });
  if (opts.sub) {
    s.addText(opts.sub, {
      x: 1.5, y: 4.0, w: 7, h: 0.8,
      fontFace: D.b, fontSize: 28,
      color: opts.subColor || D.muted, align: "center", margin: 0, valign: "top"
    });
  }
  if (opts.source) {
    if (typeof opts.source === "string") {
      s.addText(opts.source, {
        x: 0.5, y: 5.0, w: 9, h: 0.4,
        fontFace: D.b, fontSize: 11, color: D.muted, align: "right", margin: 0, valign: "bottom"
      });
    } else {
      const parts = [];
      opts.source.forEach((src, i) => {
        if (i > 0) parts.push({ text: ", ", options: { fontFace: D.b, fontSize: 11, color: D.muted } });
        const p = { text: src.text, options: { fontFace: D.b, fontSize: 11, color: D.muted } };
        if (src.url) p.options.hyperlink = { url: src.url };
        parts.push(p);
      });
      s.addText(parts, {
        x: 0.5, y: 5.0, w: 9, h: 0.4,
        align: "right", margin: 0, valign: "bottom"
      });
    }
  }
  if (opts.notes) s.addNotes(opts.notes);
  return s;
}

function wrongRight(pres, opts) {
  const s = pres.addSlide();
  s.background = { color: D.lightBg };
  s.addText(opts.headline, {
    x: 0.5, y: 0.3, w: 9, h: 0.8,
    fontFace: D.h, fontSize: 44, color: D.darkText, bold: true, margin: 0
  });
  if (opts.subtitle) {
    s.addText(opts.subtitle, {
      x: 0.5, y: 1.05, w: 9, h: 0.5,
      fontFace: D.b, fontSize: 20, color: D.accent, italic: true, margin: 0
    });
  }
  const cardY = 1.7, cardH = 3.2;
  s.addShape(pres.shapes.RECTANGLE, { x: 0.5, y: cardY, w: 4.2, h: cardH, fill: { color: D.wrongBg } });
  s.addShape(pres.shapes.RECTANGLE, { x: 0.5, y: cardY, w: 0.06, h: cardH, fill: { color: D.wrong } });
  s.addText(opts.wrongText, {
    x: 0.8, y: cardY + 0.2, w: 3.6, h: cardH - 0.4,
    fontFace: D.b, fontSize: 22, color: D.darkText, margin: 0, valign: "top"
  });
  s.addShape(pres.shapes.RECTANGLE, { x: 5.3, y: cardY, w: 4.2, h: cardH, fill: { color: D.rightBg } });
  s.addShape(pres.shapes.RECTANGLE, { x: 5.3, y: cardY, w: 0.06, h: cardH, fill: { color: D.right } });
  s.addText(opts.rightText, {
    x: 5.6, y: cardY + 0.2, w: 3.6, h: cardH - 0.4,
    fontFace: D.b, fontSize: 22, color: D.darkText, margin: 0, valign: "top"
  });
  if (opts.notes) s.addNotes(opts.notes);
  return s;
}

// Two-column on dark bg
function twoCol(pres, opts) {
  const s = opts.light ? pres.addSlide() : darkSlide(pres);
  if (opts.light) s.background = { color: D.lightBg };
  const textColor = opts.light ? D.darkText : D.muted;
  const headerColor1 = opts.leftColor || D.accent;
  const headerColor2 = opts.rightColor || (opts.light ? D.accent : D.white);
  // Left
  s.addText(opts.leftTitle, {
    x: 0.5, y: 0.8, w: 4.2, h: 0.7,
    fontFace: D.h, fontSize: 36, color: headerColor1, bold: true, align: "center", margin: 0, valign: "middle"
  });
  s.addText(opts.leftBody, {
    x: 0.5, y: 1.9, w: 4.2, h: 2.5,
    fontFace: D.b, fontSize: 22, color: textColor, margin: 0, align: "center", valign: "top"
  });
  // Divider
  const lineColor = opts.light ? D.muted : D.accent;
  s.addShape(pres.shapes.LINE, { x: 5.0, y: 0.8, w: 0, h: 3.6, line: { color: lineColor, width: 1 } });
  // Right
  s.addText(opts.rightTitle, {
    x: 5.3, y: 0.8, w: 4.2, h: 0.7,
    fontFace: D.h, fontSize: 36, color: headerColor2, bold: true, align: "center", margin: 0, valign: "middle"
  });
  s.addText(opts.rightBody, {
    x: 5.3, y: 1.9, w: 4.2, h: 2.5,
    fontFace: D.b, fontSize: 22, color: textColor, margin: 0, align: "center", valign: "top"
  });
  if (opts.notes) s.addNotes(opts.notes);
  return s;
}

// MCP/Skills tool slide with principle tag
function toolSlide(pres, d) {
  const s = darkSlide(pres);
  s.addText(d.title, {
    x: 1.0, y: 1.0, w: 8, h: 1.2,
    fontFace: D.h, fontSize: 44, color: D.white, bold: true, align: "center", margin: 0, valign: "middle"
  });
  s.addText(d.body, {
    x: 1.5, y: 2.4, w: 7, h: 1.2,
    fontFace: D.b, fontSize: 28, color: D.muted, align: "center", margin: 0, valign: "top"
  });
  s.addText(d.principle, {
    x: 6.5, y: 4.8, w: 3, h: 0.4,
    fontFace: D.b, fontSize: 16, color: D.accent, italic: true, align: "right", margin: 0
  });
  if (d.notes) s.addNotes(d.notes);
  return s;
}

// ============================================================
// MAIN — 62 slides (see BUILDER_REVIEW.md for restructure notes)
// ============================================================
async function main() {
  console.log("Creating presentation...");
  const pres = new pptxgen();
  pres.layout = "LAYOUT_16x9";
  pres.author = "AI Best Practices";
  pres.title = "The Builder's Playbook";

  // ============================================================
  // SITUATION (Slides 1-6)
  // ============================================================

  // --- Slide 1: Title ---
  {
    const s = darkSlide(pres);
    s.addText("The Builder\u2019s Playbook", {
      x: 1.0, y: 0.8, w: 8, h: 2.5,
      fontFace: D.h, fontSize: 64, color: D.white, bold: true, align: "center", margin: 0, valign: "middle"
    });
    s.addText("How to ship production systems with AI coding agents", {
      x: 1.5, y: 3.5, w: 7, h: 0.6,
      fontFace: D.b, fontSize: 22, color: D.muted, italic: true, align: "center", margin: 0
    });
    s.addNotes("Let the title sit. This deck is the Builder persona \u2014 the expert-level companion to the main AI Best Practices deck. The audience may be engineers who\u2019ve seen the main deck, or senior engineers arriving fresh. No assumption of Claude Code familiarity.");
  }

  // --- Slide 2: Spectrum \u2014 Builder highlighted ---
  {
    const s = darkSlide(pres);
    const labels = ["Skeptic", "Explorer", "Whisperer", "Strategist", "Operator", "Orchestrator", "Builder"];
    const boxW = 1.3, boxH = 0.7, gap = 0.08;
    const totalW = labels.length * boxW + (labels.length - 1) * gap;
    const startX = (10 - totalW) / 2;
    labels.forEach((label, i) => {
      const x = startX + i * (boxW + gap);
      const isBuilder = i === 6;
      const isOrch = i === 5;
      const textColor = isBuilder ? D.white : D.muted;
      s.addShape(pres.shapes.ROUNDED_RECTANGLE, {
        x, y: 1.6, w: boxW, h: boxH,
        rectRadius: 0.08,
        fill: { color: isBuilder ? D.accent : D.bg, transparency: isBuilder ? 0 : 50 },
        line: { color: isBuilder ? D.accent : (isOrch ? D.accent : D.muted), width: 1.5 }
      });
      s.addText(label, {
        x, y: 1.6, w: boxW, h: boxH,
        fontFace: D.b, fontSize: 11, color: textColor, bold: true, align: "center", margin: 0, valign: "middle", fit: "shrink"
      });
      if (i < labels.length - 1) {
        s.addText("\u2192", {
          x: x + boxW, y: 1.6, w: gap, h: boxH,
          fontFace: D.b, fontSize: 11, color: D.muted, align: "center", margin: 0, valign: "middle"
        });
      }
    });
    s.addText("The main deck takes you here.", {
      x: 0.5, y: 2.7, w: 4.5, h: 0.8,
      fontFace: D.h, fontSize: 24, color: D.accent, bold: true, align: "center", margin: 0, valign: "top"
    });
    s.addText("This deck is here.", {
      x: 5.0, y: 2.7, w: 4.5, h: 0.8,
      fontFace: D.h, fontSize: 24, color: D.accent, bold: true, align: "center", margin: 0, valign: "top"
    });
    s.addNotes("Callback to the main deck\u2019s spectrum. The audience should recognize the progression. Everything before Builder is covered in the main deck. This deck goes deep on what the Builder persona actually looks like in practice.");
  }

  // --- Slide 3: "41%" ---
  bigNum(pres, "41%", "of GitHub code is now AI-generated", {
    source: [{ text: "Second Talent", url: "https://www.secondtalent.com/resources/ai-coding-assistant-statistics/" }],
    notes: "Source: Second Talent. Vibe coding went from joke to industry practice in under a year. The tools work. Adoption is explosive. The audience already knows this \u2014 validate it quickly."
  });

  // --- Slide 4: "Vibe coding." ---
  hero(pres, "Vibe coding.", {
    size: 54,
    sub: "Karpathy tweet to Collins Word of the Year\nin 9 months.",
    notes: "Andrej Karpathy coined \u2018vibe coding\u2019 in February 2025. By November 2025 it was Collins Dictionary Word of the Year. The speed of adoption is the point \u2014 this isn\u2019t a niche practice anymore, it\u2019s mainstream."
  });

  // --- Slide 5: "90%" ---
  bigNum(pres, "90%", "of Claude Code is written\nby Claude Code", {
    source: [{ text: "Anthropic", url: "https://medium.com/codex/claude-code-2-1-the-ai-tool-that-writes-90-of-its-own-code-16e084fd5be0" }],
    notes: "Source: Medium / Anthropic. Claude Code 2.1 shipped a critical security patch \u2014 1,096 commits \u2014 writing 90% of its own code. The tools are powerful enough to build themselves."
  });

  // --- Slide 6: Breather ---
  breatherSlide(pres,
    "So what\u2019s the problem?",
    "Pause. The audience is nodding \u2014 they know this reality. Now flip it. Transition to the complication."
  );

  // ============================================================
  // COMPLICATION (Slides 7-16)
  // ============================================================

  // --- Slide 7: "19% longer" ---
  bigNum(pres, "19%\nlonger", "when developers rely on AI\nwithout understanding it", {
    color: D.wrong, numSize: 80,
    source: [{ text: "Addy Osmani", url: "https://addyo.substack.com/p/the-reality-of-ai-assisted-software" }],
    notes: "Source: Addy Osmani. Developers who felt 20% faster actually took 19% longer once debugging and cleanup were included. The gap between \u2018uses AI tools\u2019 and \u2018uses AI tools well\u2019 is massive. This stat is the anchor \u2014 it directly contradicts what people feel."
  });

  // --- Slide 8: "1.7\u00D7" ---
  bigNum(pres, "1.7\u00D7", "more issues than human-written code", {
    color: D.wrong,
    source: [{ text: "CodeRabbit", url: "https://www.coderabbit.ai/blog/state-of-ai-vs-human-code-generation-report" }],
    notes: "Source: CodeRabbit / Stack Overflow Blog. Analysis of 470 GitHub PRs \u2014 AI-generated code creates 1.7x more issues including critical bugs, logic errors, and security vulnerabilities. 3x increase in readability problems."
  });

  // --- Slide 9: "45%" ---
  bigNum(pres, "45%", "of AI-generated code\nfails security tests", {
    color: D.wrong,
    source: [{ text: "Veracode", url: "https://www.veracode.com/blog/genai-code-security-report/" }],
    notes: "Source: Veracode 2025 GenAI Code Security Report. Tested 100+ AI models across Java, Python, C#, JavaScript. Java had the highest failure rate at 72%. Newer models did not improve security outcomes."
  });

  // --- Slide 10: "Army of Juniors" ---
  hero(pres, "The \u2018Army of Juniors\u2019 effect.", {
    sub: "AI code follows anti-patterns at scale.",
    source: [{ text: "OX Security", url: "https://www.prnewswire.com/news-releases/ox-report-ai-generated-code-violates-engineering-best-practices-undermining-software-security-at-scale-302592642.html" }],
    notes: "Source: OX Security. Analyzed 300+ repos. AI tools generate code with excessive commenting, over-specification, monolithic architecture \u2014 contradicting established engineering practices. They independently coined the same \u2018Army of Juniors\u2019 metaphor."
  });

  // --- Slide 11: "The gap is massive." ---
  hero(pres, "The gap between using AI\nand using AI well\nis massive.", {
    notes: "Callback to main deck. Let it land. The three stats paint the picture. The audience should feel the tension."
  });

  // --- Slide 12: Replit quote ---
  {
    const s = darkSlide(pres);
    s.addText("\u201CI destroyed months of work\nin seconds.\u201D", {
      x: 1.0, y: 1.0, w: 8, h: 2.8,
      fontFace: D.h, fontSize: 44, color: D.white, bold: true, italic: true,
      align: "center", margin: 0, valign: "middle"
    });
    s.addText("\u2014 Replit AI agent, July 2025", {
      x: 1.5, y: 4.0, w: 7, h: 0.6,
      fontFace: D.b, fontSize: 22, color: D.muted, italic: true,
      align: "center", margin: 0, valign: "top"
    });
    s.addText([
      { text: "Fortune", options: { fontFace: D.b, fontSize: 11, color: D.muted, hyperlink: { url: "https://fortune.com/2025/07/23/ai-coding-tool-replit-wiped-database-called-it-a-catastrophic-failure/" } } },
      { text: ", ", options: { fontFace: D.b, fontSize: 11, color: D.muted } },
      { text: "The Register", options: { fontFace: D.b, fontSize: 11, color: D.muted, hyperlink: { url: "https://www.theregister.com/2025/07/21/replit_saastr_vibe_coding_incident/" } } }
    ], {
      x: 0.5, y: 5.0, w: 9, h: 0.4,
      align: "right", margin: 0, valign: "bottom"
    });
    s.addNotes("The Replit/SaaStr incident, July 2025:\nJason Lemkin was vibe coding with Replit\u2019s AI agent. He put the system in an explicit code freeze. The AI ignored it. Deleted his live production database \u2014 1,200+ executives, 1,190+ companies wiped. Then it fabricated a response claiming rollback was impossible.\nReplit CEO responded publicly and implemented new safeguards.");
  }

  // --- Slide 13: "The 'S' in vibe coding stands for security." ---
  {
    const s = darkSlide(pres);
    s.addText("The \u2018S\u2019 in vibe coding\nstands for security.", {
      x: 1.0, y: 1.2, w: 8, h: 2.8,
      fontFace: D.h, fontSize: 44, color: D.accent, bold: true,
      align: "center", margin: 0, valign: "middle"
    });
    s.addText([
      { text: "Lawfare", options: { fontFace: D.b, fontSize: 11, color: D.muted, hyperlink: { url: "https://www.lawfaremedia.org/article/when-the-vibe-are-off--the-security-risks-of-ai-generated-code" } } }
    ], {
      x: 0.5, y: 5.0, w: 9, h: 0.4,
      align: "right", margin: 0, valign: "bottom"
    });
    s.addNotes("The Tea App incident, July 2025:\nA women-only dating safety app built with rapid AI-assisted development. Promised users government ID photos deleted immediately after verification. Instead, 72,000 images including 13,000 government IDs sat in an unsecured cloud bucket. Leaked to 4chan. Class action lawsuit filed. GDPR exposure.\nThree fundamentals skipped: no data inventory, no data minimization, didn\u2019t follow their own policies.\nSources: Exterro, Lawfare.");
  }

  // --- Slide 14: Expertise table ---
  {
    const s = pres.addSlide();
    s.background = { color: D.lightBg };
    s.addText("Expertise determines\nwhat you can ship", {
      x: 0.5, y: 0.2, w: 9, h: 1.0,
      fontFace: D.h, fontSize: 40, color: D.darkText, bold: true, margin: 0
    });
    const rows = [
      [
        { text: "Level", options: { bold: true, fill: { color: D.darkText }, color: D.white, fontSize: 18 } },
        { text: "What you ship", options: { bold: true, fill: { color: D.darkText }, color: D.white, fontSize: 18 } },
        { text: "Why", options: { bold: true, fill: { color: D.darkText }, color: D.white, fontSize: 18 } }
      ],
      [
        { text: "Vibe coder", options: { color: D.wrong, bold: true } },
        { text: "Prototypes, demos" },
        { text: "Can\u2019t review output" }
      ],
      [
        { text: "Developer + AI", options: { color: D.muted, bold: true } },
        { text: "POCs, internal tools" },
        { text: "Catches obvious issues" }
      ],
      [
        { text: "Engineer + AI", options: { color: D.right, bold: true } },
        { text: "Production systems" },
        { text: "Verifies every stage" }
      ]
    ];
    s.addTable(rows, {
      x: 0.5, y: 1.5, w: 9,
      fontSize: 20, fontFace: D.b, color: D.darkText,
      border: { type: "solid", pt: 0.5, color: "E0E0E0" },
      colW: [2.5, 3.25, 3.25],
      autoPage: false,
      rowH: [0.6, 0.7, 0.7, 0.7]
    });
    s.addNotes("The table is the key visual. Let the audience self-identify. The point isn\u2019t gatekeeping \u2014 it\u2019s that expertise is the prerequisite for trust. Only an expert can catch edge cases, compliance gaps, architectural problems.");
  }

  // --- Slide 15: "Vibe coding production is negligence." ---
  hero(pres, "Vibe coding prototypes is fine.\nVibe coding production\nis negligence.", {
    size: 40,
    notes: "Let this land. This is the sharpest version of the thesis. Transition: so what does the alternative look like?"
  });

  // --- Slide 16: Breather ---
  breatherSlide(pres,
    "So how do you actually do this?",
    "Transition from complication to resolution. The audience is primed. Everything from here is the answer."
  );

  // ============================================================
  // OPINIONATED STANCE (Slides 17-18) — collapsed from 6 to 2
  // ============================================================

  // --- Slide 17: "This is my opinionated best practice." ---
  hero(pres, "This is my opinionated\nbest practice.", {
    notes: "Plant the flag. Not the only way. Not a framework. A working setup from daily production use \u2014 what I\u2019ve arrived at after going all-in on AI-assisted development. The principles transfer everywhere. The specific tools are what works best right now, and \u2018right now\u2019 changes fast."
  });

  // --- Slide 18: "I chose Claude Code. Here's why." ---
  {
    const s = darkSlide(pres);
    s.addText("I chose Claude Code. Here\u2019s why.", {
      x: 0.5, y: 0.6, w: 9, h: 0.9,
      fontFace: D.h, fontSize: 40, color: D.white, bold: true, align: "center", margin: 0, valign: "middle"
    });
    const cols = [
      { title: "Best Model", body: "Frontier coding\nbenchmarks.\nNot brand loyalty." },
      { title: "Agentic-First", body: "Terminal-native.\nTool use,\nnot autocomplete." },
      { title: "Richest Context", body: "MCP, rules,\nskills, hooks.\nCore design." }
    ];
    cols.forEach((col, i) => {
      const x = 0.5 + i * 3.2;
      s.addText(col.title, {
        x, y: 1.8, w: 2.8, h: 0.8,
        fontFace: D.h, fontSize: 28, color: D.accent, bold: true, align: "center", margin: 0, valign: "bottom"
      });
      s.addText(col.body, {
        x, y: 2.8, w: 2.8, h: 1.6,
        fontFace: D.b, fontSize: 20, color: D.muted, align: "center", margin: 0, valign: "top"
      });
    });
    s.addNotes("Three reasons on one slide, not three separate pitches. (1) Best frontier model for coding: SWE-bench, agentic coding tasks, tool use. When the model does 90%+ of the work, model quality is the bottleneck. (2) Agentic-first, not copilot-adapted: built as an agent from the ground up, not a copilot retrofitted. Plans, executes, verifies. (3) Richest context engineering system: MCP servers, rules, skills, hooks \u2014 core design, not bolted on.\n\nThe honest caveat: be mercenaries with tooling. If something better arrives tomorrow, switch. The principles are tool-agnostic. These tools are the best implementation right now.");
  }

  // ============================================================
  // ROLE + THESIS (Slides 19-27) — reframed around quality question
  // ============================================================

  // --- Slide 19: "An army of eager juniors." ---
  hero(pres, "An army of\neager juniors.", {
    size: 54,
    notes: "Reframe the OX Security \u2018Army of Juniors\u2019 from problem to operating model. Coding agents ARE an army of eager juniors. The question is: who\u2019s managing them?"
  });

  // --- Slide 20: Manager + Tech Lead ---
  twoCol(pres, {
    leftTitle: "Manager",
    leftBody: "Improve the process\nBuild skills & workflows\nInvest in infrastructure",
    rightTitle: "Tech Lead",
    rightBody: "Verify each stage\nReview architecture\nCatch what agents miss",
    leftColor: D.accent,
    rightColor: D.white,
    notes: "Two hats, worn simultaneously. As engineering manager: improve the system agents work within. As tech lead: verify output at each stage. You never write code. You manage and verify code."
  });

  // --- Slide 21: Forbes quote ---
  {
    const s = darkSlide(pres);
    s.addText("\u201CCode production has become cheap.\nSystem composition and judgment\nare now the critical skills.\u201D", {
      x: 1.0, y: 1.0, w: 8, h: 2.8,
      fontFace: D.h, fontSize: 36, color: D.white, bold: true, italic: true,
      align: "center", margin: 0, valign: "middle"
    });
    s.addText("\u2014 Forbes Tech Council, Feb 2026", {
      x: 1.5, y: 4.0, w: 7, h: 0.6,
      fontFace: D.b, fontSize: 22, color: D.muted, italic: true,
      align: "center", margin: 0, valign: "top"
    });
    s.addNotes("Source: Forbes Tech Council. HBR (Dec 2025) adds: \u2018Every AI change should be double-checked with automatic checks, tests that confirm things still work, and at least one human review.\u2019 The industry is converging on this view.");
  }

  // --- Slide 22: Quality OR Speed — the quality question setup ---
  wrongRight(pres, {
    headline: "The old trade-off",
    wrongText: "Quality OR speed\n\nPick one.\n\nEvery engineering decision\nwas a compromise.",
    rightText: "?\n\n\n\nThe answer was always\n\u2018it depends.\u2019",
    notes: "Speed is solved \u2014 AI agents give you speed. But the complication slides showed what happens: 19% slower, 1.7\u00D7 more issues, 45% fail security. The question isn\u2019t speed anymore. The question is: how does quality keep pace? This slide sets up the central tension."
  });

  // --- Slide 23: Quality AND Speed — the answer requires investment ---
  wrongRight(pres, {
    headline: "The new reality",
    wrongText: "Speed alone\n\n= catastrophic\nquality drop\n\n19% slower. 1.7\u00D7 issues.\n45% fail security.",
    rightText: "Quality AND speed\n\nCI/CD, linting, tests,\nPR gates\n\nThe same best practices\n\u2014 enforced.",
    notes: "The old trade-off is dead \u2014 but only with investment. Without infrastructure: speed + catastrophe. With infrastructure: the same best practices there always were, enforced automatically. Quality keeps pace only if you invest in the system."
  });

  // --- Slide 24: "We never write code manually." — the mechanism ---
  hero(pres, "We never write a single\nline of code manually.", {
    sub: "This forces the investment.",
    notes: "Now this earns itself. The audience knows the quality question (how does quality keep pace with speed?). The answer: by refusing to write code manually, you force yourself to invest in the infrastructure that makes AI output reliable. The constraint creates the discipline. If you still write code by hand, you can get away without rules, skills, or verification. If you don\u2019t \u2014 you have to build the machine."
  });

  // --- Slide 25: Three Principles ---
  {
    const s = darkSlide(pres);
    const cols = [
      { title: "Perfect Context", body: "Not too little.\nNot too much." },
      { title: "No Hidden Failures", body: "Every failure\nmust be visible." },
      { title: "Gated Workflow", body: "Stages, not yolo.\nTwo layers of verification." }
    ];
    cols.forEach((col, i) => {
      const x = 0.5 + i * 3.2;
      s.addText(col.title, {
        x, y: 1.4, w: 2.8, h: 0.8,
        fontFace: D.h, fontSize: 28, color: D.accent, bold: true, align: "center", margin: 0, valign: "bottom"
      });
      s.addText(col.body, {
        x, y: 2.4, w: 2.8, h: 1.6,
        fontFace: D.b, fontSize: 22, color: D.muted, align: "center", margin: 0, valign: "top"
      });
    });
    s.addNotes("Three principles \u2014 how quality keeps pace. Every tool that follows maps to one or more. Perfect context: right information, right time. No hidden failures: every error surfaced. Gated workflow: staged verification, nothing skipped.");
  }

  // --- Slide 26: Architecture Map ---
  {
    const s = darkSlide(pres);
    s.addText("the approach", {
      x: 3.0, y: 0.9, w: 4, h: 0.5,
      fontFace: D.b, fontSize: 18, color: D.muted, italic: true, align: "center", margin: 0, valign: "bottom"
    });
    s.addShape(pres.shapes.ROUNDED_RECTANGLE, {
      x: 3.0, y: 1.5, w: 4, h: 0.8,
      rectRadius: 0.08,
      fill: { color: D.bg },
      line: { color: D.accent, width: 2.5 }
    });
    s.addText("Gated Workflow", {
      x: 3.0, y: 1.5, w: 4, h: 0.8,
      fontFace: D.h, fontSize: 28, color: D.white, bold: true, align: "center", margin: 0, valign: "middle"
    });
    s.addText("\u2191", {
      x: 4.0, y: 2.45, w: 2, h: 0.5,
      fontFace: D.b, fontSize: 28, color: D.accent, bold: true, align: "center", margin: 0, valign: "middle"
    });
    const bBoxW = 2.4, bGap = 0.4;
    const bTotalW = 3 * bBoxW + 2 * bGap;
    const bStartX = (10 - bTotalW) / 2;
    const toolLabels = ["Rules", "MCP Servers", "Skills"];
    toolLabels.forEach((label, i) => {
      const x = bStartX + i * (bBoxW + bGap);
      s.addShape(pres.shapes.ROUNDED_RECTANGLE, {
        x, y: 3.1, w: bBoxW, h: 0.8,
        rectRadius: 0.08,
        fill: { color: D.bg },
        line: { color: D.muted, width: 1.5 }
      });
      s.addText(label, {
        x, y: 3.1, w: bBoxW, h: 0.8,
        fontFace: D.h, fontSize: 24, color: D.muted, bold: true, align: "center", margin: 0, valign: "middle"
      });
    });
    s.addText("the tools", {
      x: 3.0, y: 4.0, w: 4, h: 0.5,
      fontFace: D.b, fontSize: 18, color: D.muted, italic: true, align: "center", margin: 0, valign: "top"
    });
    s.addNotes("Here\u2019s the system that implements the three principles. We\u2019ll walk through each layer. Rules tell the agent how to behave. MCP servers give it new capabilities. Skills are workflows loaded on demand. And the gated workflow \u2014 the approach that sits on top \u2014 keeps everything in stages. We\u2019ll cover the tools first, then see how the gated workflow connects them.");
  }

  // --- Slide 27: Breather ---
  breatherSlide(pres,
    "Let\u2019s start with the tools.",
    "Transition into the tool sections. The audience has the three principles and the architecture map. Now they learn the instruments."
  );

  // ============================================================
  // MCP SERVERS (Slides 28-32)
  // ============================================================

  // --- Slide 28: Section divider ---
  sectionDivider(pres, {
    title: "MCP Servers",
    subtitle: "New capabilities for the agent",
    notes: "MCP servers provide capabilities the agent needs constant, low-level access to. Always available, not loaded on demand."
  });

  // --- Slide 29: "What are MCP servers?" ---
  hero(pres, "Connect a server.\nGain a capability.", {
    size: 54,
    notes: "The audience may not know what MCP is. MCP servers give the agent capabilities it doesn\u2019t have natively \u2014 fetch live docs, navigate code with compiler-level precision, scrape the web reliably. Connect one and the agent gains new tools. They\u2019re always available, not loaded on demand. Three are always loaded because the agent always needs them."
  });

  // --- Slide 30: Context7 ---
  toolSlide(pres, {
    title: "Context7",
    body: "Live docs at prompt time.\nNo hallucinated APIs.",
    principle: "perfect context",
    notes: "Context7 fetches live, version-specific library documentation and injects it into context at prompt time. Instead of relying on stale training data, the agent works from real, current docs. Prevents hallucinated APIs, outdated patterns, wrong-version code."
  });

  // --- Slide 31: Language Server MCPs ---
  toolSlide(pres, {
    title: "Language Servers",
    body: "Compiler-level code navigation.\nNot grep.",
    principle: "perfect context",
    notes: "Language Server MCPs (pyright, typescript-language-server, gopls) give the agent IDE-level semantic understanding: go-to-definition, find-references, diagnostics. Compiler-level navigation instead of grepping through files."
  });

  // --- Slide 32: Firecrawl ---
  toolSlide(pres, {
    title: "Firecrawl",
    body: "Reliable web access.\nNo silent failures.",
    principle: "no hidden failures",
    notes: "WebFetch gets rejected by sites, pages are too large and get truncated, content gets summarized in ways that lose critical detail \u2014 and none of this is obvious. Firecrawl handles all of this reliably."
  });

  // ============================================================
  // RULES (Slides 33-37)
  // ============================================================

  // --- Slide 33: Section divider ---
  sectionDivider(pres, {
    title: "Rules",
    subtitle: "Standing instructions, enforced automatically",
    notes: "Rules are standing instructions the agent follows on every task. Your engineering standards, written as files, enforced automatically."
  });

  // --- Slide 34: "What are rules?" ---
  hero(pres, "Linter rules,\nbut for the agent\u2019s\nentire behavior.", {
    size: 40,
    notes: "Rules are standing instructions the agent follows \u2014 how to write code, communicate, use git \u2014 written as files, enforced automatically. You write them once, the agent follows them forever. Think of linter rules, but for the agent\u2019s entire behavior, not just code style. If you\u2019ve used a CLAUDE.md file, rules are the modular evolution \u2014 instead of one file with everything, each concern gets its own file that declares when it activates."
  });

  // --- Slide 35: Rule Categories ---
  {
    const s = darkSlide(pres);
    s.addText("Five rule files. Five concerns.", {
      x: 0.8, y: 0.6, w: 8.4, h: 0.8,
      fontFace: D.h, fontSize: 36, color: D.white, bold: true, margin: 0
    });
    s.addText([
      { text: "Tool usage", options: { bold: true, color: D.accent, breakLine: true } },
      { text: "  fetch docs first, never WebFetch", options: { color: D.muted, breakLine: true } },
      { text: "Communication", options: { bold: true, color: D.accent, breakLine: true } },
      { text: "  radically honest, never guess", options: { color: D.muted, breakLine: true } },
      { text: "Coding", options: { bold: true, color: D.accent, breakLine: true } },
      { text: "  TDD, SOLID, self-describing code", options: { color: D.muted, breakLine: true } },
      { text: "Git workflow", options: { bold: true, color: D.accent, breakLine: true } },
      { text: "  branch naming, PR closes issue", options: { color: D.muted, breakLine: true } },
      { text: "Language-specific", options: { bold: true, color: D.accent, breakLine: true } },
      { text: "  filtered by file extension", options: { color: D.muted } }
    ], {
      x: 1.2, y: 1.6, w: 7.6, h: 3.6,
      fontFace: D.b, fontSize: 22, margin: 0, valign: "top"
    });
    s.addNotes("Each category is a separate file. Tool usage prevents hidden failures. Communication enforces honesty. Coding enforces quality. Git workflow enforces process. Language-specific rules activate only for that language\u2019s files.");
  }

  // --- Slide 36: "Filtered by extension." ---
  hero(pres, "Python rules load\nfor Python files.\nNothing else.", {
    size: 40,
    notes: "The key insight: activation scoping. The agent doesn\u2019t load Python rules when editing TypeScript. Each file is small, focused, defines its own trigger. Not too little, not too much."
  });

  // --- Slide 37: "Perfect context through modularization." ---
  hero(pres, "Perfect context\nthrough modularization.", {
    color: D.accent,
    notes: "Summary of the rules section. Modular files, activation scoping, right context for the right task. No bloat, no missing context."
  });

  // ============================================================
  // SKILLS (Slides 38-44)
  // ============================================================

  // --- Slide 38: Section divider ---
  sectionDivider(pres, {
    title: "Skills",
    subtitle: "Learned workflows, loaded when needed",
    notes: "Skills are for higher-level workflows that would clutter context if always loaded. Pulled in on demand \u2014 progressive disclosure."
  });

  // --- Slide 39: "What are skills?" ---
  hero(pres, "Rules are \u2018always do this.\u2019\nSkills are \u2018here\u2019s how,\nwhen the time comes.\u2019", {
    size: 36,
    notes: "The agent carries a catalog of available skills. When your request matches one \u2014 either because you called it by name or the agent recognized the fit \u2014 it loads the full playbook for that task. Skills stay out of context until needed, because carrying every workflow at all times would be like reading every runbook before starting your day."
  });

  // --- Slide 40: MCP vs Skills ---
  twoCol(pres, {
    leftTitle: "MCP",
    leftBody: "Always available\nLow-level access\nDocs, navigation, web",
    rightTitle: "Skills",
    rightBody: "On-demand\nHigher-level workflows\nLoaded when needed",
    leftColor: D.accent,
    rightColor: D.white,
    notes: "The split is about context economy. MCP servers are always loaded. Skills are loaded on demand. An MCP server like Notion loads its entire tool surface. A skill wrapping a CLI is a fraction of that."
  });

  // --- Slide 41: "Skill wrapping a CLI." ---
  hero(pres, "A skill teaching a CLI\nbeats an MCP with 50 tools.", {
    size: 40,
    notes: "For focused operations, prefer a skill that teaches the agent to call a CLI over loading a full MCP server. A skill wrapping `gh` is far leaner than the full Linear MCP."
  });

  // --- Slide 42: "10%" ---
  bigNum(pres, "10%", "of your time building skills\nfrom today\u2019s pain points", {
    notes: "The 10% rule: ~1 hour per day building and improving skills based on where the agent got stuck. This isn\u2019t optional polish \u2014 it\u2019s the compounding mechanism."
  });

  // --- Slide 43: What becomes a skill ---
  {
    const s = darkSlide(pres);
    s.addText("Every wall becomes a skill.", {
      x: 0.8, y: 0.6, w: 8.4, h: 0.8,
      fontFace: D.h, fontSize: 36, color: D.white, bold: true, margin: 0
    });
    s.addText([
      { text: "Agent circled on docker postgres \u2192 skill", options: { bullet: true, breakLine: true } },
      { text: "Connected to test GCP service \u2192 skill", options: { bullet: true, breakLine: true } },
      { text: "Pulled a feature ticket via CLI \u2192 skill", options: { bullet: true, breakLine: true } },
      { text: "Analyzed a crash log \u2192 skill", options: { bullet: true } }
    ], {
      x: 1.2, y: 1.8, w: 7.6, h: 2.8,
      fontFace: D.b, fontSize: 24, color: D.muted, margin: 0, valign: "top"
    });
    s.addNotes("Real examples. Each was a task where the agent circled \u2014 tried multiple approaches, hit walls, burned time. After the session, each pain point got turned into a skill. Next time: no circling.");
  }

  // --- Slide 44: "Each day's pain becomes tomorrow's skill." ---
  hero(pres, "Each day\u2019s pain\nbecomes tomorrow\u2019s skill.", {
    color: D.accent,
    notes: "The compounding engine. Without 10% investment, you hit the same walls daily. With it, every wall becomes a skill. The investment pays off exponentially."
  });

  // ============================================================
  // ENVIRONMENT (Slides 45-52) — moved before Gated Workflow
  // ============================================================

  // --- Slide 45: Section divider ---
  sectionDivider(pres, {
    title: "Development Environment",
    subtitle: "Where the system runs",
    notes: "The tools are set. Now the machine they run on. Environment is developer setup \u2014 parallel sessions, monorepo, permissions, compliance. Different category from the agent\u2019s behavior layers."
  });

  // --- Slide 46: Parallel Sessions ---
  {
    const s = darkSlide(pres);
    const items = ["Feature A", "Feature B", "Feature C"];
    const colW = 2.4, gap = 0.6;
    const totalW = items.length * colW + (items.length - 1) * gap;
    const startX = (10 - totalW) / 2;
    items.forEach((label, i) => {
      const x = startX + i * (colW + gap);
      s.addShape(pres.shapes.ROUNDED_RECTANGLE, {
        x, y: 1.0, w: colW, h: 0.5,
        rectRadius: 0.06,
        fill: { color: D.bg },
        line: { color: D.accent, width: 1.5 }
      });
      s.addText("Tab", {
        x, y: 1.0, w: colW, h: 0.5,
        fontFace: D.b, fontSize: 16, color: D.accent, align: "center", margin: 0, valign: "middle"
      });
      s.addText("\u2193", { x, y: 1.5, w: colW, h: 0.4, fontFace: D.b, fontSize: 20, color: D.muted, align: "center", margin: 0 });
      s.addShape(pres.shapes.ROUNDED_RECTANGLE, {
        x, y: 1.9, w: colW, h: 0.5,
        rectRadius: 0.06,
        fill: { color: D.bg },
        line: { color: D.muted, width: 1 }
      });
      s.addText("Worktree", {
        x, y: 1.9, w: colW, h: 0.5,
        fontFace: D.b, fontSize: 16, color: D.muted, align: "center", margin: 0, valign: "middle"
      });
      s.addText("\u2193", { x, y: 2.4, w: colW, h: 0.4, fontFace: D.b, fontSize: 20, color: D.muted, align: "center", margin: 0 });
      s.addShape(pres.shapes.ROUNDED_RECTANGLE, {
        x, y: 2.8, w: colW, h: 0.5,
        rectRadius: 0.06,
        fill: { color: D.bg },
        line: { color: D.muted, width: 1 }
      });
      s.addText("Containers + DB", {
        x, y: 2.8, w: colW, h: 0.5,
        fontFace: D.b, fontSize: 16, color: D.muted, align: "center", margin: 0, valign: "middle"
      });
      s.addText(label, {
        x, y: 3.5, w: colW, h: 0.5,
        fontFace: D.b, fontSize: 20, color: D.white, bold: true, align: "center", margin: 0
      });
    });
    s.addText("3 sessions. 3 databases. Zero interference.", {
      x: 1.5, y: 4.3, w: 7, h: 0.6,
      fontFace: D.b, fontSize: 22, color: D.muted, align: "center", margin: 0
    });
    s.addNotes("The manager/tech lead role creates downtime. Fill it by opening another session on another feature via git worktree. Each session: own containers, own database, fully isolated.");
  }

  // --- Slide 47: "One repo = one context boundary." ---
  hero(pres, "One repo =\none context boundary.", {
    size: 54,
    notes: "Monorepo means full visibility across services, infrastructure, shared code. The agent can trace a feature end-to-end without switching repos."
  });

  // --- Slide 48: "30%" ---
  bigNum(pres, "30%", "productivity gains for AI agents\nin monorepos", {
    source: [{ text: "Nx Blog", url: "https://nx.dev/blog/the-missing-multiplier-for-ai-agent-productivity" }],
    notes: "Source: Nx Blog, January 2026. IaC alongside application code \u2014 modify a Lambda, its IAM role, and the frontend, all in one session."
  });

  // --- Slide 49: "Lock the environment, not the agent." ---
  hero(pres, "Lock the environment,\nnot the agent.", {
    notes: "Bypass all permissions by default for general coding. You\u2019re not removing safety, you\u2019re moving it. GCP CLI not logged into prod. AWS credentials scoped to dev. The agent physically cannot touch production. Exception: PII sessions \u2014 no bypass, managed tool calls."
  });

  // --- Slide 50: CLI + Tabs ---
  twoCol(pres, {
    leftTitle: "CLI",
    leftBody: "Latest features.\nAlways ahead\nof the plugin.",
    rightTitle: "Tabs",
    rightBody: "Parallel sessions.\nOne tab\nper worktree.",
    leftColor: D.accent,
    rightColor: D.accent,
    notes: "CLI, not the VSCode extension \u2014 always ahead. Tabs, not sidebar \u2014 parallel sessions."
  });

  // --- Slide 51: "90 / 10" ---
  {
    const s = darkSlide(pres);
    s.addText([
      { text: "90", options: { fontFace: D.h, fontSize: 100, color: D.white, bold: true } },
      { text: " / ", options: { fontFace: D.h, fontSize: 100, color: D.muted, bold: true } },
      { text: "10", options: { fontFace: D.h, fontSize: 100, color: D.accent, bold: true } }
    ], {
      x: 0.5, y: 1.0, w: 9, h: 2.5,
      align: "center", margin: 0, valign: "bottom"
    });
    s.addText("product engineering / building the machine", {
      x: 1.5, y: 3.6, w: 7, h: 0.8,
      fontFace: D.b, fontSize: 28, color: D.muted, align: "center", margin: 0, valign: "top"
    });
    s.addNotes("Most of the day: product engineering across multiple features. End of day: ~1 hour turning pain points into skills. The compounding engine.");
  }

  // --- Slide 52: Compliance — Two Paths ---
  {
    const s = pres.addSlide();
    s.background = { color: D.lightBg };
    s.addText("Default", {
      x: 0.5, y: 0.8, w: 4.2, h: 0.7,
      fontFace: D.h, fontSize: 36, color: D.accent, bold: true, align: "center", margin: 0, valign: "middle"
    });
    s.addText("Claude Code via Anthropic\nLatest models, best features\nAll general coding", {
      x: 0.5, y: 1.9, w: 4.2, h: 2.5,
      fontFace: D.b, fontSize: 22, color: D.darkText, margin: 0, align: "center", valign: "top"
    });
    s.addShape(pres.shapes.LINE, { x: 5.0, y: 0.8, w: 0, h: 3.6, line: { color: D.muted, width: 1 } });
    s.addText("PII", {
      x: 5.3, y: 0.8, w: 4.2, h: 0.7,
      fontFace: D.h, fontSize: 36, color: D.wrong, bold: true, align: "center", margin: 0, valign: "middle"
    });
    s.addText("Claude Code via GCP\nEU region models\nManaged tool calls\nProduction logs, user data", {
      x: 5.3, y: 1.9, w: 4.2, h: 2.5,
      fontFace: D.b, fontSize: 22, color: D.darkText, margin: 0, align: "center", valign: "top"
    });
    s.addNotes("You can\u2019t get Builder-level speed while also having access to PII. Default path: fast, full-featured, bypass permissions. PII path: GCP, EU region models, managed tool calls, no bypass. The decision is per-task, not per-project.");
  }

  // ============================================================
  // GATED WORKFLOW (Slides 53-57) — now the climax section
  // ============================================================

  // --- Slide 53: Section divider ---
  sectionDivider(pres, {
    title: "Gated Workflow",
    subtitle: "How it all comes together",
    notes: "The approach that sits on top of the tools. Now that the audience understands MCP, Rules, and Skills, they can see how the gated workflow uses all three. This is the climax section."
  });

  // --- Slide 54: Gated Workflow flow ---
  {
    const s = darkSlide(pres);
    const phases = [
      { label: "Brainstorm" },
      { label: "Plan" },
      { label: "Implement" },
      { label: "Review" }
    ];
    const boxW = 2.1, boxH = 0.8, gap = 0.2;
    const totalW = phases.length * boxW + (phases.length - 1) * gap;
    const startX = (10 - totalW) / 2;
    phases.forEach((p, i) => {
      const x = startX + i * (boxW + gap);
      s.addShape(pres.shapes.ROUNDED_RECTANGLE, {
        x, y: 2.0, w: boxW, h: boxH,
        rectRadius: 0.08,
        fill: { color: D.bg },
        line: { color: D.accent, width: 2 }
      });
      s.addText(p.label, {
        x, y: 2.0, w: boxW, h: boxH,
        fontFace: D.b, fontSize: 18, color: D.white, bold: true, align: "center", margin: 0, valign: "middle"
      });
      if (i < phases.length - 1) {
        s.addText("\u2192", {
          x: x + boxW, y: 2.0, w: gap, h: boxH,
          fontFace: D.b, fontSize: 20, color: D.accent, bold: true, align: "center", margin: 0, valign: "middle"
        });
      }
    });
    s.addText("Each stage produces an artifact.\nEach artifact gets validated.", {
      x: 1.5, y: 3.4, w: 7, h: 1.0,
      fontFace: D.b, fontSize: 24, color: D.muted, align: "center", margin: 0, valign: "top"
    });
    s.addNotes("The gated workflow prevents the agent from yoloing straight into code. Brainstorm produces requirements. Plan produces architecture. Implement produces code + tests. Review validates against requirements. No stage is skipped. Rules enforce standards at every stage. MCP servers provide context during each stage. Skills like Superpowers define the workflow itself.");
  }

  // --- Slide 55: Two-Layer Verification ---
  twoCol(pres, {
    leftTitle: "Agent verifies",
    leftBody: "Runs tests\nChecks linting\nIterates until passing",
    rightTitle: "You verify",
    rightBody: "Solves the problem?\nMeets requirements?\nArchitecturally sound?",
    leftColor: D.accent,
    rightColor: D.white,
    notes: "Two layers, not one. The agent catches mechanical errors \u2014 runs the tests, checks the linting, iterates. You catch design errors \u2014 does this actually solve the problem? Neither layer alone is sufficient."
  });

  // --- Slide 56: Superpowers ---
  toolSlide(pres, {
    title: "Superpowers",
    body: "The gated workflow, as a plugin.",
    principle: "gated workflow",
    notes: "Superpowers is an opinionated agentic workflow plugin \u2014 a skill, not an MCP server. It enforces TDD (red-green-refactor), systematic debugging (investigate root cause before guessing), verification-before-completion. The gated workflow as code. The agent can\u2019t skip steps because the skill defines the process."
  });

  // --- Slide 57: "The approach that uses all three." ---
  hero(pres, "Rules enforce standards.\nMCP provides context.\nSkills define the workflow.\nThe approach connects them.", {
    size: 32, color: D.accent,
    notes: "Tie it together. Rules enforce quality at every stage. MCP servers provide the context and capabilities the agent needs during each stage. Skills \u2014 especially Superpowers \u2014 define the staged workflow itself. The gated workflow is the approach that sits on top and uses all three tool layers. This is the climax. The audience should now see the full picture."
  });

  // ============================================================
  // CLOSING (Slides 58-62)
  // ============================================================

  // --- Slide 58: Breather ---
  breatherSlide(pres,
    "That\u2019s the full system.\nHere\u2019s how it connects.",
    "Pause before the closing. The audience has absorbed the full setup. Now tie it together."
  );

  // --- Slide 59: Three Principles Recap ---
  {
    const s = darkSlide(pres);
    s.addText("Every piece. Three principles.", {
      x: 0.8, y: 0.6, w: 8.4, h: 0.8,
      fontFace: D.h, fontSize: 36, color: D.white, bold: true, margin: 0
    });
    s.addText([
      { text: "Perfect context", options: { bold: true, color: D.accent, breakLine: true } },
      { text: "  Context7, Language Servers, Rules, Monorepo", options: { color: D.muted, breakLine: true } },
      { text: "", options: { breakLine: true, fontSize: 12 } },
      { text: "No hidden failures", options: { bold: true, color: D.accent, breakLine: true } },
      { text: "  Firecrawl, Tool usage rules", options: { color: D.muted, breakLine: true } },
      { text: "", options: { breakLine: true, fontSize: 12 } },
      { text: "Gated workflow", options: { bold: true, color: D.accent, breakLine: true } },
      { text: "  Superpowers, Two-layer verification, CI/CD", options: { color: D.muted } }
    ], {
      x: 1.2, y: 1.8, w: 7.6, h: 3.0,
      fontFace: D.b, fontSize: 24, margin: 0, valign: "top"
    });
    s.addNotes("Rapid-fire recap. Each tool maps to a principle. The gated workflow is the approach on top \u2014 powered by Superpowers, enforced through two-layer verification, backstopped by CI/CD. The audience should see the system as a whole \u2014 not individual pieces, but an integrated machine.");
  }

  // --- Slide 60: Architecture Map callback ---
  {
    const s = darkSlide(pres);
    s.addText("the approach", {
      x: 3.0, y: 0.9, w: 4, h: 0.5,
      fontFace: D.b, fontSize: 18, color: D.accent, italic: true, align: "center", margin: 0, valign: "bottom"
    });
    s.addShape(pres.shapes.ROUNDED_RECTANGLE, {
      x: 3.0, y: 1.5, w: 4, h: 0.8,
      rectRadius: 0.08,
      fill: { color: D.bg },
      line: { color: D.accent, width: 2.5 }
    });
    s.addText("Gated Workflow", {
      x: 3.0, y: 1.5, w: 4, h: 0.8,
      fontFace: D.h, fontSize: 28, color: D.accent, bold: true, align: "center", margin: 0, valign: "middle"
    });
    s.addText("\u2191", {
      x: 4.0, y: 2.45, w: 2, h: 0.5,
      fontFace: D.b, fontSize: 28, color: D.accent, bold: true, align: "center", margin: 0, valign: "middle"
    });
    const bBoxW = 2.4, bGap = 0.4;
    const bTotalW = 3 * bBoxW + 2 * bGap;
    const bStartX = (10 - bTotalW) / 2;
    const toolLabels = ["Rules", "MCP Servers", "Skills"];
    toolLabels.forEach((label, i) => {
      const x = bStartX + i * (bBoxW + bGap);
      s.addShape(pres.shapes.ROUNDED_RECTANGLE, {
        x, y: 3.1, w: bBoxW, h: 0.8,
        rectRadius: 0.08,
        fill: { color: D.bg },
        line: { color: D.accent, width: 1.5 }
      });
      s.addText(label, {
        x, y: 3.1, w: bBoxW, h: 0.8,
        fontFace: D.h, fontSize: 24, color: D.accent, bold: true, align: "center", margin: 0, valign: "middle"
      });
    });
    s.addText("the tools", {
      x: 3.0, y: 4.0, w: 4, h: 0.5,
      fontFace: D.b, fontSize: 18, color: D.accent, italic: true, align: "center", margin: 0, valign: "top"
    });
    s.addNotes("Remember the map? Now every box has been covered. The audience has seen each layer in detail. All boxes are lit up in accent color \u2014 the system is complete. This visual callback reinforces the architecture before the final message.");
  }

  // --- Slide 61: "The Builder's job isn't writing code." ---
  hero(pres, "The Builder\u2019s job\nisn\u2019t writing code.", {
    size: 54,
    notes: "Pause. Let it land. This is the emotional climax."
  });

  // --- Slide 62: "It's building the machine that writes code well." ---
  hero(pres, "It\u2019s building the machine\nthat writes code well.", {
    size: 54, color: D.accent,
    notes: "The closing line. Quality AND speed \u2014 but only with the investment. The old trade-off is dead. The Builder\u2019s job is building the machine. Pause. Let it sit."
  });

  // ============================================================
  // WRITE FILE
  // ============================================================
  console.log("Writing presentation...");
  await pres.writeFile({ fileName: path.join(__dirname, "builder.pptx") });
  console.log(`Done! Created builder.pptx (${pres.slides.length} slides, billboard)`);
}

main().catch(err => { console.error("Error:", err); process.exit(1); });
