// Generated by deckwright — this script produces ai-policy.pptx
// Edit THIS FILE, not the .pptx. Changes to ai-policy.pptx will be
// overwritten the next time this script runs.
//
// Run: node ai-policy.js

const pptxgen = require("pptxgenjs");
const path = require("path");

// ============================================================
// DESIGN SYSTEM (identical to main ai-best-practices deck)
// ============================================================
const D = {
  bg: "0A2540", lightBg: "FFFFFF", glow: "635BFF",
  white: "FFFFFF", text: "EDEDED", muted: "8B95A5", darkText: "1A1F36",
  accent: "635BFF", wrong: "FF6B8A", wrongBg: "FEE2E8", right: "09825D", rightBg: "DCFCE7",
  h: "Georgia", b: "Verdana",
};

// ============================================================
// UTILITIES
// ============================================================
function darkSlide(pres) {
  const s = pres.addSlide();
  s.background = { color: D.bg };
  s.addShape(pres.shapes.OVAL, {
    x: 5, y: 2.5, w: 8, h: 6,
    fill: { color: D.accent, transparency: 96 }
  });
  return s;
}

function breatherSlide(pres, text, notes) {
  const s = darkSlide(pres);
  s.addText(text, {
    x: 1.5, y: 2.0, w: 7, h: 1.6,
    fontFace: D.h, fontSize: 28, color: D.accent, italic: true,
    align: "center", margin: 0, valign: "middle"
  });
  if (notes) s.addNotes(notes);
  return s;
}

function sectionDivider(pres, d) {
  const s = darkSlide(pres);
  s.addText(d.title, {
    x: 0.5, y: 1.6, w: 9, h: 1.2,
    fontFace: D.h, fontSize: 54, color: D.white, bold: true, align: "center", margin: 0
  });
  if (d.subtitle) {
    s.addText(d.subtitle, {
      x: 1.0, y: 2.9, w: 8, h: 0.6,
      fontFace: D.b, fontSize: 28, color: D.accent, italic: true, align: "center", margin: 0
    });
  }
  s.addNotes(d.notes || "");
  return s;
}

function bigNum(pres, num, sub, opts = {}) {
  const s = darkSlide(pres);
  const numColor = opts.color || D.white;
  s.addText(num, {
    x: 0.5, y: 1.0, w: 9, h: 2.5,
    fontFace: D.h, fontSize: opts.numSize || 120,
    color: numColor, bold: true, align: "center", margin: 0, valign: "bottom"
  });
  s.addText(sub, {
    x: 1.5, y: 3.6, w: 7, h: 0.8,
    fontFace: D.b, fontSize: 28,
    color: D.muted, align: "center", margin: 0, valign: "top"
  });
  if (opts.source) {
    if (typeof opts.source === "string") {
      s.addText(opts.source, {
        x: 0.5, y: 5.0, w: 9, h: 0.4,
        fontFace: D.b, fontSize: 11, color: D.muted, align: "right", margin: 0, valign: "bottom"
      });
    } else {
      const parts = [];
      opts.source.forEach((src, i) => {
        if (i > 0) parts.push({ text: ", ", options: { fontFace: D.b, fontSize: 11, color: D.muted } });
        const p = { text: src.text, options: { fontFace: D.b, fontSize: 11, color: D.muted } };
        if (src.url) p.options.hyperlink = { url: src.url };
        parts.push(p);
      });
      s.addText(parts, {
        x: 0.5, y: 5.0, w: 9, h: 0.4,
        align: "right", margin: 0, valign: "bottom"
      });
    }
  }
  if (opts.notes) s.addNotes(opts.notes);
  return s;
}

function hero(pres, main, opts = {}) {
  const s = darkSlide(pres);
  s.addText(main, {
    x: 1.0, y: 0.8, w: 8, h: 2.8,
    fontFace: opts.font || D.h, fontSize: opts.size || 44,
    color: opts.color || D.white, bold: true,
    align: "center", margin: 0, valign: "middle"
  });
  if (opts.sub) {
    s.addText(opts.sub, {
      x: 1.5, y: 4.2, w: 7, h: 0.8,
      fontFace: D.b, fontSize: 24,
      color: opts.subColor || D.muted, align: "center", margin: 0, valign: "top"
    });
  }
  if (opts.source) {
    if (typeof opts.source === "string") {
      s.addText(opts.source, {
        x: 0.5, y: 5.0, w: 9, h: 0.4,
        fontFace: D.b, fontSize: 11, color: D.muted, align: "right", margin: 0, valign: "bottom"
      });
    } else {
      const parts = [];
      opts.source.forEach((src, i) => {
        if (i > 0) parts.push({ text: ", ", options: { fontFace: D.b, fontSize: 11, color: D.muted } });
        const p = { text: src.text, options: { fontFace: D.b, fontSize: 11, color: D.muted } };
        if (src.url) p.options.hyperlink = { url: src.url };
        parts.push(p);
      });
      s.addText(parts, {
        x: 0.5, y: 5.0, w: 9, h: 0.4,
        align: "right", margin: 0, valign: "bottom"
      });
    }
  }
  if (opts.notes) s.addNotes(opts.notes);
  return s;
}

function wrongRight(pres, opts) {
  const s = pres.addSlide();
  s.background = { color: D.lightBg };
  s.addText(opts.headline, {
    x: 0.5, y: 0.3, w: 9, h: 0.8,
    fontFace: D.h, fontSize: 44, color: D.darkText, bold: true, margin: 0
  });
  if (opts.subtitle) {
    s.addText(opts.subtitle, {
      x: 0.5, y: 1.05, w: 9, h: 0.5,
      fontFace: D.b, fontSize: 20, color: D.accent, italic: true, margin: 0
    });
  }
  const cardY = 1.7, cardH = 3.2;
  s.addShape(pres.shapes.RECTANGLE, { x: 0.5, y: cardY, w: 4.2, h: cardH, fill: { color: D.wrongBg } });
  s.addShape(pres.shapes.RECTANGLE, { x: 0.5, y: cardY, w: 0.06, h: cardH, fill: { color: D.wrong } });
  s.addText(opts.wrongText, {
    x: 0.8, y: cardY + 0.2, w: 3.6, h: cardH - 0.4,
    fontFace: D.b, fontSize: 22, color: D.darkText, margin: 0, valign: "top"
  });
  s.addShape(pres.shapes.RECTANGLE, { x: 5.3, y: cardY, w: 4.2, h: cardH, fill: { color: D.rightBg } });
  s.addShape(pres.shapes.RECTANGLE, { x: 5.3, y: cardY, w: 0.06, h: cardH, fill: { color: D.right } });
  s.addText(opts.rightText, {
    x: 5.6, y: cardY + 0.2, w: 3.6, h: cardH - 0.4,
    fontFace: D.b, fontSize: 22, color: D.darkText, margin: 0, valign: "top"
  });
  if (opts.notes) s.addNotes(opts.notes);
  return s;
}

function twoCol(pres, opts) {
  const s = opts.light ? pres.addSlide() : darkSlide(pres);
  if (opts.light) s.background = { color: D.lightBg };
  const textColor = opts.light ? D.darkText : D.muted;
  const headerColor1 = opts.leftColor || D.accent;
  const headerColor2 = opts.rightColor || (opts.light ? D.accent : D.white);
  s.addText(opts.leftTitle, {
    x: 0.5, y: 0.8, w: 4.2, h: 0.7,
    fontFace: D.h, fontSize: 36, color: headerColor1, bold: true, align: "center", margin: 0, valign: "middle"
  });
  s.addText(opts.leftBody, {
    x: 0.5, y: 1.9, w: 4.2, h: 2.5,
    fontFace: D.b, fontSize: 22, color: textColor, margin: 0, align: "center", valign: "top"
  });
  const lineColor = opts.light ? D.muted : D.accent;
  s.addShape(pres.shapes.LINE, { x: 5.0, y: 0.8, w: 0, h: 3.6, line: { color: lineColor, width: 1 } });
  s.addText(opts.rightTitle, {
    x: 5.3, y: 0.8, w: 4.2, h: 0.7,
    fontFace: D.h, fontSize: 36, color: headerColor2, bold: true, align: "center", margin: 0, valign: "middle"
  });
  s.addText(opts.rightBody, {
    x: 5.3, y: 1.9, w: 4.2, h: 2.5,
    fontFace: D.b, fontSize: 22, color: textColor, margin: 0, align: "center", valign: "top"
  });
  if (opts.notes) s.addNotes(opts.notes);
  return s;
}

// ============================================================
// MAIN
// ============================================================
async function main() {
  console.log("Creating presentation...");
  const pres = new pptxgen();
  pres.layout = "LAYOUT_16x9";
  pres.author = "AI Best Practices";
  pres.title = "AI Tools & Your Business: A Policy Guide";

  // ============================================================
  // SITUATION (Slides 1-5)
  // ============================================================

  // --- Slide 1: Title ---
  {
    const s = darkSlide(pres);
    s.addText("AI Tools & Your Business", {
      x: 1.0, y: 0.8, w: 8, h: 2.5,
      fontFace: D.h, fontSize: 64, color: D.white, bold: true, align: "center", margin: 0, valign: "middle"
    });
    s.addText("A guide to choosing the right AI setup for your company", {
      x: 1.5, y: 3.3, w: 7, h: 0.6,
      fontFace: D.b, fontSize: 22, color: D.muted, italic: true, align: "center", margin: 0
    });
    s.addText("For informational purposes only \u2014 not legal advice", {
      x: 1.5, y: 4.2, w: 7, h: 0.4,
      fontFace: D.b, fontSize: 14, color: D.muted, align: "center", margin: 0
    });
    s.addText("Last verified: February 2026", {
      x: 1.5, y: 4.7, w: 7, h: 0.4,
      fontFace: D.b, fontSize: 11, color: D.muted, align: "center", margin: 0
    });
    s.addNotes("This is a self-serve reference deck for decision makers who are responsible for AI tooling choices but are not compliance or technical experts. Provider policies change frequently \u2014 always check current documentation before making decisions. Nothing in this deck constitutes legal advice; it is intended to help companies ask the right questions and make informed choices. Consult qualified legal counsel before implementing any policy.");
  }

  // --- Slide 2: Your team is already using AI ---
  hero(pres, "Your team is already using AI.", {
    size: 54,
    sub: "The question is whether you know how.",
    notes: "AI adoption isn\u2019t a future initiative \u2014 it\u2019s already happening. Employees are using free ChatGPT, personal Claude accounts, and whatever tools they find. The company may think it\u2019s \u201Cnot doing AI yet.\u201D It is."
  });

  // --- Slide 3: Two scenarios ---
  twoCol(pres, {
    leftTitle: "Just ChatGPT",
    leftBody: "No official tools\nEmployees use free tiers\nNo policy, no oversight\nYou think you\u2019re not doing AI",
    rightTitle: "Wild West",
    rightBody: "Too many tools\nEvery team picked their own\nNo coordination\nNobody checked the data policies",
    leftColor: D.accent,
    rightColor: D.white,
    notes: "Both scenarios are problems. The first has no visibility \u2014 employees are using free tools with no DPA, data potentially entering training pipelines. The second embraced AI aggressively but nobody coordinated: engineering has Claude Code, marketing uses ChatGPT Plus, finance runs analysis in Claude, ops evaluates insurance claims in ChatGPT. Neither scenario has a deliberate AI policy."
  });

  // --- Slide 4: AI touches every department ---
  hero(pres, "Engineering. Finance.\nMarketing. Operations.\nEveryone.", {
    size: 42,
    sub: "AI is every department\u2019s problem now.",
    notes: "Engineering: Claude Code, Codex, Copilot. Finance: ChatGPT or Claude Code for analysis. Marketing: content generation, copy assistance. Operations: evaluating claims, processing requests. Everyone: email drafting, research, summarisation. \u201CVibe coding\u201D isn\u2019t just for engineers anymore \u2014 non-technical staff are using Claude Code to build analysis tools, internal scripts, and automations without engineering guardrails."
  });

  // --- Slide 5: Breather ---
  breatherSlide(pres,
    "So what\u2019s the risk?",
    "Pause. The audience understands the situation \u2014 AI is everywhere. Now flip it. What happens when it goes wrong?"
  );

  // ============================================================
  // COMPLICATION (Slides 6-14)
  // ============================================================

  // --- Slide 6: Samsung incident ---
  {
    const s = darkSlide(pres);
    s.addText("Samsung engineers pasted\nproprietary code into ChatGPT.", {
      x: 1.0, y: 1.0, w: 8, h: 2.4,
      fontFace: D.h, fontSize: 40, color: D.white, bold: true,
      align: "center", margin: 0, valign: "middle"
    });
    s.addText("Company-wide ban followed.", {
      x: 1.5, y: 3.6, w: 7, h: 0.8,
      fontFace: D.b, fontSize: 28, color: D.muted, align: "center", margin: 0, valign: "top"
    });
    s.addText([
      { text: "Business Insider, 2023", options: { fontFace: D.b, fontSize: 11, color: D.muted, hyperlink: { url: "https://www.businessinsider.com/samsung-chatgpt-leak-2023-4" } } }
    ], {
      x: 0.5, y: 5.0, w: 9, h: 0.4,
      align: "right", margin: 0, valign: "bottom"
    });
    s.addNotes("Samsung, 2023. Engineers pasted proprietary source code and confidential meeting notes into free ChatGPT. The data entered OpenAI\u2019s training pipeline. Samsung banned ChatGPT company-wide. The leak wasn\u2019t a hack or a breach \u2014 it was an employee pasting code into a free tool. Source: Business Insider.");
  }

  // --- Slide 7: Tea App incident ---
  hero(pres, "72,000 photos.\n13,000 government IDs.\nLeaked to 4chan.", {
    size: 44, color: D.wrong,
    source: [{ text: "Lawfare, 2025", url: "https://www.lawfaremedia.org/article/when-the-vibe-are-off--the-security-risks-of-ai-generated-code" }],
    notes: "The Tea App, 2025. A dating safety app built with rapid AI-assisted development. Promised users their government ID photos would be deleted immediately after verification. Instead, 72,000 images \u2014 including 13,000 government IDs \u2014 sat in an unsecured cloud bucket. Leaked to 4chan. Class action lawsuit filed. Three fundamentals were skipped: no data inventory, no data minimisation, no follow-through on their own policies. Source: Lawfare."
  });

  // --- Slide 8: EUR 15M fine ---
  bigNum(pres, "\u20AC15M", "first GDPR fine targeting\na generative AI company", {
    color: D.wrong,
    source: [{ text: "Reuters, Dec 2024", url: "https://www.reuters.com/technology/italy-fines-openai-15-million-euros-over-privacy-rules-breach-2024-12-20/" }],
    notes: "Italy\u2019s Garante fined OpenAI EUR 15 million in December 2024 for processing EU users\u2019 data for model training without a lawful basis, insufficient transparency, and no age verification for minors. This was the first GDPR enforcement action specifically targeting a generative AI company. The EDPB ChatGPT Taskforce investigation remains ongoing across multiple EU member states. Source: Reuters."
  });

  // --- Slide 9: Common thread ---
  hero(pres, "None required\na sophisticated attack.", {
    size: 54,
    notes: "The common thread across all three incidents: no hacking, no breach, no sophisticated attack. Samsung was an employee pasting code. The Tea App was skipped fundamentals. The fine was a policy failure. These were all failures of deliberate choice \u2014 the absence of a deliberate AI policy."
  });

  // --- Slide 10: Transition to rules ---
  breatherSlide(pres,
    "Five rules every decision maker\nneeds to know.",
    "Transition. The audience has seen what can go wrong. Now give them the knowledge to prevent it. These five rules are a simplified summary for non-experts \u2014 not exhaustive legal guidance. Consult qualified counsel for specific obligations."
  );

  // --- Slide 11: Rules 1-3 ---
  {
    const s = darkSlide(pres);
    s.addText("The rules that matter", {
      x: 0.5, y: 0.3, w: 9, h: 0.9,
      fontFace: D.h, fontSize: 40, color: D.white, bold: true, margin: 0
    });
    const rules = [
      { num: "1", title: "Typing data into an AI tool = processing it", desc: "GDPR applies the moment personal data enters a prompt" },
      { num: "2", title: "Your company is liable, not the tool", desc: "You\u2019re the data controller. The AI provider is the processor." },
      { num: "3", title: "Free tiers are a different legal world", desc: "No DPA, may train on your data, no deletion controls" }
    ];
    const textParts = [];
    rules.forEach((rule, i) => {
      textParts.push({ text: rule.num + "  ", options: { bold: true, color: D.accent, fontSize: 24, fontFace: D.b } });
      textParts.push({ text: rule.title, options: { bold: true, color: D.white, fontSize: 22, fontFace: D.b, breakLine: true } });
      textParts.push({ text: "     " + rule.desc, options: { color: D.muted, fontSize: 20, fontFace: D.b, breakLine: true } });
      if (i < rules.length - 1) {
        textParts.push({ text: "", options: { fontSize: 12, breakLine: true } });
      }
    });
    s.addText(textParts, {
      x: 0.7, y: 1.4, w: 8.6, h: 3.8,
      margin: 0, valign: "top"
    });
    s.addNotes("Rule 1: \u201CProcessing\u201D under GDPR means any operation on personal data. Every prompt with a customer name is a processing event. Rule 2: The \u201Cdata controller\u201D carries primary legal liability \u2014 that\u2019s your company, not OpenAI or Anthropic. Rule 3: Enterprise tiers have DPAs, no-training guarantees, and compliance controls. Free/consumer tiers have none of this. Same tool, completely different legal standing.");
  }

  // --- Slide 12: Rules 4-5 + fines ---
  {
    const s = darkSlide(pres);
    const rules = [
      { num: "4", title: "Data has to stay protected when it crosses borders", desc: "A DPA governs the relationship. It doesn\u2019t control geography." },
      { num: "5", title: "AI literacy training is now law", desc: "EU AI Act Article 4. Enforceable now. Not a suggestion." }
    ];
    const textParts = [];
    rules.forEach((rule, i) => {
      textParts.push({ text: rule.num + "  ", options: { bold: true, color: D.accent, fontSize: 24, fontFace: D.b } });
      textParts.push({ text: rule.title, options: { bold: true, color: D.white, fontSize: 22, fontFace: D.b, breakLine: true } });
      textParts.push({ text: "     " + rule.desc, options: { color: D.muted, fontSize: 20, fontFace: D.b, breakLine: true } });
      if (i < rules.length - 1) {
        textParts.push({ text: "", options: { fontSize: 12, breakLine: true } });
      }
    });
    s.addText(textParts, {
      x: 0.7, y: 0.5, w: 8.6, h: 2.8,
      margin: 0, valign: "top"
    });
    s.addText("Fines: up to 4% global turnover (GDPR) or 7% (EU AI Act)", {
      x: 0.7, y: 3.8, w: 8.6, h: 0.7,
      fontFace: D.b, fontSize: 18, color: D.wrong, bold: true, margin: 0
    });
    s.addNotes("Rule 4: EU personal data sent to US servers needs legal cover \u2014 Standard Contractual Clauses (SCCs) are valid but carry residual Schrems-style risk. EU data residency (data never leaves the EU) is the stronger posture. A DPA alone does not solve this. Rule 5: EU AI Act Article 4 requires AI literacy training for all staff using AI tools \u2014 this is enforceable now, not a future requirement. Fines can reach 4% of global annual turnover under GDPR (Article 83) or 7% under the EU AI Act for prohibited practices (Article 99). This is a simplified summary \u2014 consult legal counsel for your specific obligations.");
  }

  // --- Slide 13: Paying != protected ---
  hero(pres, "Paying \u2260 protected.", {
    size: 54, color: D.accent,
    sub: "The tier matters. Not the price tag.",
    notes: "This is the single most common misconception. Decision makers assume \u201Cwe\u2019re paying for Claude Pro / ChatGPT Plus, so we\u2019re covered.\u201D They\u2019re not. The terms, DPA, and compliance controls depend entirely on which tier you\u2019re on \u2014 not whether you\u2019re paying."
  });

  // --- Slide 14: Consumer vs Enterprise tiers ---
  twoCol(pres, {
    leftTitle: "Consumer Tiers",
    leftBody: "Training allowed\nNo DPA\nNo deletion controls",
    rightTitle: "Enterprise Tiers",
    rightBody: "No training (contractual)\nDPA with EU SCCs\nCompliance controls",
    leftColor: D.wrong,
    rightColor: D.right,
    notes: "Consumer tiers: Claude Free / Pro / Max, ChatGPT Free / Plus, GitHub Copilot Free. Enterprise tiers: Claude Team / Enterprise / API, ChatGPT Business / Enterprise, GitHub Copilot Business+. Claude Pro ($20/month) is under Anthropic\u2019s Consumer Terms \u2014 training IS allowed (with opt-out), no DPA applies. Only Team/Enterprise/API are under Commercial Terms. Same at OpenAI: Plus trains by default. Same at GitHub: Free tier allows training on your code."
  });

  // ============================================================
  // PROVIDER COMPARISON (Slides 15-25)
  // ============================================================

  // --- Slide 15: Transition to provider choice ---
  breatherSlide(pres,
    "Platform or direct provider?\nTwo paths. One structural choice.",
    "Transition. The audience has seen why tiers matter \u2014 now introduce the structural choice EU companies face: an EU-native platform that sits in front of multiple models (like Langdock), or a direct relationship with a US provider\u2019s enterprise tier. The platform option is new to most readers \u2014 make this framing clear before the comparison slides."
  );

  // --- Slide 16: EU-native platform — consider this first ---
  {
    const s = pres.addSlide();
    s.background = { color: D.lightBg };
    s.addText("Consider an EU-native platform first", {
      x: 0.5, y: 0.2, w: 9, h: 1.2,
      fontFace: D.h, fontSize: 40, color: D.darkText, bold: true, margin: 0
    });
    s.addText("One DPA with an EU company. EU data residency by default. Every major model.", {
      x: 0.5, y: 1.6, w: 9, h: 0.45,
      fontFace: D.b, fontSize: 18, color: D.accent, margin: 0
    });
    s.addText([
      { text: "Langdock", options: { bold: true, color: D.darkText, fontSize: 20, fontFace: D.b } },
      { text: " \u2014 German GmbH, hosted on Azure Frankfurt", options: { color: D.darkText, fontSize: 20, fontFace: D.b, breakLine: true } }
    ], {
      x: 0.5, y: 2.15, w: 9, h: 0.55,
      margin: 0, valign: "top"
    });
    s.addText("ISO 27001 \u00B7 SOC 2 Type II \u00B7 GDPR-native DPA \u00B7 No model training", {
      x: 0.5, y: 2.8, w: 9, h: 0.4,
      fontFace: D.b, fontSize: 18, color: D.muted, margin: 0
    });
    s.addText("30+ models: Claude Opus 4.6, GPT-5, Gemini 2.5 Pro, Mistral \u2014 many in EU regions", {
      x: 0.5, y: 3.3, w: 9, h: 0.5,
      fontFace: D.b, fontSize: 18, color: D.darkText, margin: 0
    });
    s.addText("~\u20AC23.20/user/month \u00B7 Merck, Der Spiegel, Personio, Volksbank", {
      x: 0.5, y: 3.88, w: 9, h: 0.4,
      fontFace: D.b, fontSize: 16, color: D.muted, margin: 0
    });
    s.addText([
      { text: "langdock.com/security", options: { fontFace: D.b, fontSize: 11, color: D.muted, hyperlink: { url: "https://langdock.com/security" } } }
    ], {
      x: 0.5, y: 5.0, w: 9, h: 0.4,
      align: "right", margin: 0, valign: "bottom"
    });
    s.addNotes("Langdock is a German GmbH, hosted on Microsoft Azure in Frankfurt \u2014 EU data residency is the default on the standard tier, not an enterprise add-on to negotiate for. No training on customer data. One DPA with an EU company (not US-based providers relying on SCCs). Supports 30+ models: Claude Opus 4.6/Sonnet 4.6, GPT-5 series, Gemini 2.5 Pro/Flash, Mistral Large, Llama \u2014 with many available in EU regions. One interface for chat, agents, workflows, and integrations. Used by Merck (33,000 MAU), Der Spiegel, Personio, Volksbank, Eppendorf, SumUp, 5,000+ companies. Trade-off: adding a platform vendor, though it replaces multiple vendor relationships. If you have strong model preferences or existing enterprise contracts, a direct provider may be simpler \u2014 which is what the next two slides cover. Sources: langdock.com/security, trust.langdock.com/faq.");
  }

  // --- Slide 17: Provider comparison — products & training ---
  {
    const s = pres.addSlide();
    s.background = { color: D.lightBg };
    s.addText("The provider landscape", {
      x: 0.5, y: 0.2, w: 7, h: 0.8,
      fontFace: D.h, fontSize: 40, color: D.darkText, bold: true, margin: 0
    });
    s.addText("Last verified: February 2026", {
      x: 0.5, y: 0.9, w: 7, h: 0.4,
      fontFace: D.b, fontSize: 14, color: D.accent, italic: true, margin: 0
    });
    const rows = [
      [
        { text: "", options: { bold: true, fill: { color: D.accent }, color: D.white, fontSize: 18 } },
        { text: "OpenAI", options: { bold: true, fill: { color: D.accent }, color: D.white, fontSize: 18 } },
        { text: "Anthropic", options: { bold: true, fill: { color: D.accent }, color: D.white, fontSize: 18 } },
        { text: "Google", options: { bold: true, fill: { color: D.accent }, color: D.white, fontSize: 18 } },
        { text: "Microsoft", options: { bold: true, fill: { color: D.accent }, color: D.white, fontSize: 18 } }
      ],
      [
        { text: "General use", options: { bold: true, color: D.darkText } },
        { text: "ChatGPT" },
        { text: "Claude.ai" },
        { text: "Gemini" },
        { text: "Copilot" }
      ],
      [
        { text: "Coding", options: { bold: true, color: D.darkText } },
        { text: "Codex" },
        { text: "Claude Code" },
        { text: "Code Assist" },
        { text: "GitHub Copilot" }
      ],
      [
        { text: "No-training tier", options: { bold: true, color: D.darkText } },
        { text: "Business /\nEnterprise" },
        { text: "Team /\nEnterprise / API" },
        { text: "Workspace /\nVertex" },
        { text: "M365 / GH\nBusiness+" }
      ]
    ];
    s.addTable(rows, {
      x: 0.3, y: 1.5, w: 9.4,
      fontSize: 16, fontFace: D.b, color: D.darkText,
      border: { pt: 1, color: D.muted },
      colW: [1.6, 1.9, 1.9, 1.9, 2.1],
      autoPage: false,
      rowH: [0.5, 0.55, 0.55, 0.75]
    });
    s.addNotes("Four providers dominate. Each offers both general-use assistants and coding tools. The no-training guarantee is available from all four \u2014 but only at enterprise tiers. OpenAI rebranded \u201CTeam\u201D to \u201CBusiness\u201D in 2025. Codex is now a full cloud-based agentic platform (GPT-5.3-Codex, Feb 2026), not just a coding tool. Gemini Code Assist comes in Standard and Enterprise editions. M365 Copilot is a paid add-on (~$30/user/month), not included with M365 subscriptions. Provider policies change frequently \u2014 verify current terms before acting.");
  }

  // --- Slide 17: Provider comparison — compliance & residency ---
  {
    const s = pres.addSlide();
    s.background = { color: D.lightBg };
    s.addText("Compliance & data residency", {
      x: 0.5, y: 0.2, w: 9, h: 0.8,
      fontFace: D.h, fontSize: 40, color: D.darkText, bold: true, margin: 0
    });
    const rows = [
      [
        { text: "", options: { bold: true, fill: { color: D.accent }, color: D.white, fontSize: 18 } },
        { text: "OpenAI", options: { bold: true, fill: { color: D.accent }, color: D.white, fontSize: 18 } },
        { text: "Anthropic", options: { bold: true, fill: { color: D.accent }, color: D.white, fontSize: 18 } },
        { text: "Google", options: { bold: true, fill: { color: D.accent }, color: D.white, fontSize: 18 } },
        { text: "Microsoft", options: { bold: true, fill: { color: D.accent }, color: D.white, fontSize: 18 } }
      ],
      [
        { text: "DPA", options: { bold: true, color: D.darkText } },
        { text: "Business /\nEnterprise / API" },
        { text: "Team /\nEnterprise / API" },
        { text: "Workspace /\nVertex" },
        { text: "M365 / Azure /\nGH Business+" }
      ],
      [
        { text: "EU residency", options: { bold: true, color: D.darkText } },
        { text: "Enterprise /\nEdu + API" },
        { text: "No direct\n(via GCP / AWS)" },
        { text: "Native\n(10+ EU regions)" },
        { text: "EU Boundary\n+ Azure" }
      ],
      [
        { text: "Transfer", options: { bold: true, color: D.darkText } },
        { text: "SCCs\n(no DPF)" },
        { text: "SCCs\n(Ireland entity)" },
        { text: "CDPA" },
        { text: "DPA +\nEU Boundary" }
      ]
    ];
    s.addTable(rows, {
      x: 0.3, y: 1.2, w: 9.4,
      fontSize: 15, fontFace: D.b, color: D.darkText,
      border: { pt: 1, color: D.muted },
      colW: [1.6, 1.9, 1.9, 1.9, 2.1],
      autoPage: false,
      rowH: [0.5, 0.65, 0.65, 0.65]
    });
    s.addNotes("EU data residency varies dramatically. Google: native across 10+ EU regions on Vertex AI with contractual data location commitments. OpenAI: added EU residency for Enterprise/Edu (storage at rest since Feb 2025, inference residency since Jan 2026). ChatGPT Business does NOT yet have EU residency. Microsoft: EU Data Boundary applies for M365 Copilot EU users, but Anthropic model calls and Bing web search queries are excluded (as of Jan 2026). Azure OpenAI offers EU residency via Standard/DataZone deployment. Anthropic: no direct EU residency, but Claude models available on Vertex AI and Bedrock in EU regions. Transfer mechanisms: OpenAI uses SCCs and is notably NOT DPF-certified. Anthropic uses SCCs via Anthropic Ireland Limited. Google uses its CDPA. Microsoft uses DPA + EU Data Boundary. Certification highlights: Anthropic has the broadest pure-play AI certification matrix (SOC 2 Type II, ISO 27001, ISO 42001, HIPAA, CSA STAR, NIST 800-171, FedRAMP High). All four hold ISO 42001.");
  }

  // --- Slide 18: DPA != data residency ---
  hero(pres, "A DPA \u2260 data residency.", {
    size: 54,
    sub: "One governs the relationship.\nThe other controls the geography.",
    notes: "A DPA (Data Processing Agreement) says: \u201Cyou won\u2019t train on my data\u201D and \u201Cyou\u2019ll help me with deletion requests.\u201D It does NOT control where data is physically processed. It\u2019s a governance document, not a geography document. This distinction matters because most decision makers assume \u201Cwe signed a DPA, we\u2019re compliant.\u201D A DPA is necessary but not sufficient for full compliance posture."
  });

  // --- Slide 19: DPA + SCCs vs EU data residency ---
  twoCol(pres, {
    leftTitle: "DPA + SCCs",
    leftBody: "Legally defensible\nSame as Salesforce, M365\nData goes to US servers\nSCCs invalidated twice before",
    rightTitle: "EU Data Residency",
    rightBody: "Data never leaves the EU\nNo cross-border transfer\nNo Schrems-style risk\nStronger regulatory posture",
    leftColor: D.accent,
    rightColor: D.white,
    notes: "DPA + SCCs is the standard practice for EU companies using US SaaS \u2014 legally valid, widely used, same posture as Microsoft 365 or Salesforce. The residual risk: SCCs have been invalidated before (Schrems I in 2015, Schrems II in 2020) and AI tools are under heightened regulatory scrutiny (EUR 15M OpenAI fine, EDPB ChatGPT Taskforce). EU data residency removes this risk entirely \u2014 data never leaves the EU, no Chapter V transfer to justify. Both are GDPR-legal. The difference is risk profile under supervisory authority scrutiny and whether your sector requires actual data localisation."
  });

  // --- Slide 20: 11% sensitive data ---
  bigNum(pres, "11%", "of data pasted into ChatGPT\nis sensitive", {
    color: D.wrong,
    source: [{ text: "Cyberhaven", url: "https://www.cyberhaven.com/blog/4-2-of-workers-have-pasted-company-data-into-chatgpt/" }],
    notes: "Cyberhaven research found that 11% of what employees copy and paste into ChatGPT is sensitive data \u2014 customer names, financial information, proprietary content. This is not malice; it\u2019s muscle memory. Someone drafts a customer email, pastes the thread for context, and now a real name + email + complaint details are on US servers. You cannot policy your way around human behaviour at this scale."
  });

  // --- Slide 21: Assume PII will enter ---
  hero(pres, "Assume PII will enter\nyour tools.", {
    size: 54, color: D.accent,
    sub: "Make the default path safe enough\nthat it doesn\u2019t matter.",
    notes: "The honest starting point for EU companies: you cannot prevent PII from entering AI tools. A customer name in an email draft, a real account number in a data analysis, a client\u2019s project details in a brainstorm. Instead of relying on unenforceable \u201Cdon\u2019t paste PII\u201D policies, make the default path safe enough that accidental PII exposure is already covered. This means EU data residency as the default for EU companies, not a secondary path."
  });

  // --- Slide 22: Workarounds ---
  hero(pres, "Any model, any cloud,\nEU-resident.", {
    size: 54,
    sub: "Claude on GCP \u00B7 Claude on AWS \u00B7 Azure OpenAI \u00B7 M365 Copilot",
    notes: "Claude Code on GCP: CLAUDE_CODE_USE_VERTEX=1 with EU region. Google\u2019s CDPA. 10+ EU regions (Belgium, Netherlands, Frankfurt, Zurich, Paris, Milan, Finland, Warsaw, Madrid, London). Full model lineup: Opus 4.6, Sonnet 4.6, Haiku 4.5. Claude Code on AWS: CLAUDE_CODE_USE_BEDROCK=1 with EU region (Ireland, Frankfurt). Azure OpenAI (Microsoft Foundry): Standard or DataZone deployment in EU \u2014 avoid Global deployment. M365 Copilot: EU Data Boundary automatic for EU users, but Anthropic model calls and Bing web search queries currently excluded."
  });

  // --- Slide 23: Two-path architecture ---
  twoCol(pres, {
    leftTitle: "Everyday Use",
    leftBody: "Email, research, analysis\nCustomer names will enter\nNo enforceable boundary\n\n\u2192 Default to EU-resident",
    rightTitle: "Coding",
    rightBody: "You control the data\nTest data \u2192 enterprise tier\nProduction data \u2192 EU-resident\n\n\u2192 Two paths possible",
    leftColor: D.accent,
    rightColor: D.accent,
    notes: "The two-path split only works where the data boundary is enforceable \u2014 and that\u2019s coding. For everyday use (email drafting, research, analysis), PII will enter regardless: customer names in email threads, real account numbers in analysis, client details in brainstorms. You cannot policy your way around this. For coding, the boundary is enforceable: test data vs production data is a clear technical distinction. Engineering coding new features with test data doesn\u2019t need EU residency. Debugging a production issue with real customer data does. For EU companies: default everyday use tools to EU-resident. Only coding has a practical two-path split."
  });

  // --- Slide 24: Department examples ---
  {
    const s = darkSlide(pres);
    s.addText("The boundary only works for code.", {
      x: 0.5, y: 0.3, w: 9, h: 0.9,
      fontFace: D.h, fontSize: 36, color: D.white, bold: true, margin: 0
    });
    const examples = [
      { task: "Marketing drafting a client email", path: "PII enters", pathColor: D.wrong },
      { task: "Ops evaluating a customer claim", path: "PII enters", pathColor: D.wrong },
      { task: "Engineering coding with test data", path: "no PII", pathColor: D.right },
      { task: "Engineering debugging production", path: "PII enters", pathColor: D.wrong }
    ];
    const textParts = [];
    examples.forEach((ex, i) => {
      textParts.push({ text: ex.task, options: { color: D.text, fontSize: 22, fontFace: D.b } });
      textParts.push({ text: "  \u2192  ", options: { color: D.muted, fontSize: 22, fontFace: D.b } });
      textParts.push({ text: ex.path, options: { bold: true, color: ex.pathColor, fontSize: 22, fontFace: D.b, breakLine: true } });
      if (i < examples.length - 1) {
        textParts.push({ text: "", options: { fontSize: 10, breakLine: true } });
      }
    });
    s.addText(textParts, {
      x: 0.7, y: 1.5, w: 8.6, h: 3.5,
      margin: 0, valign: "top"
    });
    s.addNotes("Only one of these four scenarios has an enforceable PII boundary: engineering coding with test data. In every other case, PII will enter the tool \u2014 customer names in marketing emails, real account details in ops claims, production customer data in debugging. The two-path split is a coding architecture decision, not a company-wide policy. For everything else, assume PII enters and choose your tools accordingly.");
  }

  // ============================================================
  // RESOLUTION (Slides 26-34)
  // ============================================================

  // --- Slide 26: Transition to resolution ---
  breatherSlide(pres,
    "Time for the actual decision.",
    "Transition. The audience has the landscape, the rules, the comparison, and the architecture. Now give them the decision framework and the concrete answer."
  );

  // --- Slide 27: Five questions ---
  {
    const s = pres.addSlide();
    s.background = { color: D.lightBg };
    s.addText("Five questions to ask\nbefore any vendor conversation", {
      x: 0.5, y: 0.15, w: 9, h: 1.0,
      fontFace: D.h, fontSize: 34, color: D.darkText, bold: true, margin: 0
    });
    const questions = [
      { q: "What data touches the tool?", desc: "PII = enterprise tier minimum. Sensitive + EU = EU residency." },
      { q: "Where are your customers?", desc: "EU customers = GDPR applies. Consider residency, not just SCCs." },
      { q: "Engineering vs everyone else?", desc: "Different departments = different risk profiles." },
      { q: "How many tools can you manage?", desc: "Every direct provider = a DPA, a tier distinction, training. Platform approach: one DPA, all models." },
      { q: "What\u2019s your compliance maturity?", desc: "No DPO? Pick the simplest path." }
    ];
    const textParts = [];
    questions.forEach((item, i) => {
      textParts.push({ text: (i + 1) + "  ", options: { bold: true, color: D.accent, fontSize: 18, fontFace: D.b } });
      textParts.push({ text: item.q, options: { bold: true, color: D.darkText, fontSize: 18, fontFace: D.b } });
      textParts.push({ text: "  " + item.desc, options: { color: D.muted, fontSize: 16, fontFace: D.b, breakLine: true } });
      if (i < questions.length - 1) {
        textParts.push({ text: "", options: { fontSize: 6, breakLine: true } });
      }
    });
    s.addText(textParts, {
      x: 0.7, y: 1.3, w: 8.6, h: 4.1,
      margin: 0, valign: "top"
    });
    s.addNotes("Question 1 is the most important \u2014 it determines minimum tier and whether EU residency matters. Question 2: EU customers = GDPR applies. Consider residency, not just SCCs. Question 3: Different departments = different risk profiles. Question 4 is what most companies underestimate: each direct provider relationship is a DPA to sign, a tier distinction to communicate to employees, and a training programme to run. For EU companies, the platform approach (Langdock) collapses this: one DPA with an EU company, one interface for employees, one admin dashboard for policy. Question 5 is about honesty \u2014 if you don\u2019t have a DPO, pick the simplest path: Langdock or one provider at enterprise tier with a signed DPA.");
  }

  // --- Slide 28: Section divider — Recommended Setup ---
  sectionDivider(pres, {
    title: "The Recommended Setup",
    subtitle: "A concrete starting point",
    notes: "This section provides an opinionated starting point for both EU and non-EU companies. These are informed suggestions based on the research in this deck \u2014 not legal advice. Have your legal team review before implementing."
  });

  // --- Slide 29: For EU companies — three paths ---
  {
    const s = pres.addSlide();
    s.background = { color: D.lightBg };
    s.addText("The recommended setup for EU companies", {
      x: 0.5, y: 0.15, w: 9, h: 1.2,
      fontFace: D.h, fontSize: 38, color: D.darkText, bold: true, margin: 0
    });
    s.addText([
      { text: "A \u2014 EU-native platform", options: { bold: true, color: D.accent, fontSize: 18, fontFace: D.b } },
      { text: "  (recommended)", options: { color: D.accent, fontSize: 14, fontFace: D.b, breakLine: true } },
      { text: "Langdock \u2014 German GmbH, Azure Frankfurt, EU residency by default, ~\u20AC23.20/user/month", options: { color: D.darkText, fontSize: 16, fontFace: D.b, breakLine: true } },
      { text: "", options: { fontSize: 6, breakLine: true } },
      { text: "B \u2014 Embedded AI", options: { bold: true, color: D.darkText, fontSize: 18, fontFace: D.b, breakLine: true } },
      { text: "M365 Copilot (~$30/user/month, EU Data Boundary) \u00B7 Workspace Gemini (native EU, CDPA)", options: { color: D.darkText, fontSize: 16, fontFace: D.b, breakLine: true } },
      { text: "", options: { fontSize: 6, breakLine: true } },
      { text: "C \u2014 Direct provider", options: { bold: true, color: D.muted, fontSize: 18, fontFace: D.b, breakLine: true } },
      { text: "ChatGPT Enterprise (EU residency available) \u00B7 Claude Team (DPA + EU SCCs, no EU residency)", options: { color: D.muted, fontSize: 16, fontFace: D.b, breakLine: true } }
    ], {
      x: 0.5, y: 1.45, w: 9, h: 3.1,
      margin: 0, valign: "top"
    });
    s.addShape(pres.shapes.LINE, {
      x: 0.5, y: 4.6, w: 9, h: 0,
      line: { color: D.muted, width: 1 }
    });
    s.addText([
      { text: "Non-EU: Claude Team or ChatGPT Business with DPA", options: { color: D.muted, fontSize: 14, fontFace: D.b, breakLine: true } },
      { text: "Coding: Claude Code via Vertex/Bedrock in EU region \u00B7 GitHub Copilot Business", options: { color: D.muted, fontSize: 14, fontFace: D.b } }
    ], {
      x: 0.5, y: 4.7, w: 9, h: 0.7,
      margin: 0, valign: "top"
    });
    s.addNotes("Option A (Langdock) is the recommended starting point for EU companies evaluating from scratch: EU-native, EU data residency out of the box, no tier complexity, one DPA with an EU company, access to 30+ models. Option B is genuinely compelling regardless of your current stack \u2014 particularly if you want to minimise vendor count and already have a Microsoft or Google enterprise agreement. Option C for companies with a strong model preference or existing contract \u2014 ChatGPT Enterprise now has full EU data residency; Claude Team is legally defensible via SCCs but has no EU data residency from Anthropic directly (use Claude models via Langdock or Claude Code on Vertex/Bedrock for EU residency). Non-EU companies: Claude Team or ChatGPT Business with DPA remains the simple default. Coding: Claude Code via Vertex AI or Bedrock in EU region; GitHub Copilot Business/Enterprise. These are informed suggestions, not legal advice.");
  }

  // --- Slide 29: The bright line ---
  hero(pres, "Free tiers are not approved\nfor work. Full stop.", {
    size: 44, color: D.wrong,
    notes: "The single highest-impact policy decision: free and consumer tiers of ANY provider are not approved for work use. This includes: free ChatGPT, Claude Free/Pro/Max (Consumer Terms \u2014 training allowed), ChatGPT Plus (trains by default), GitHub Copilot Free (training allowed), consumer Copilot without M365 login. No DPA, potential training on your data, no way to honour deletion requests."
  });

  // --- Slide 30: Six policy components ---
  {
    const s = darkSlide(pres);
    s.addText("What your AI policy needs", {
      x: 0.5, y: 0.25, w: 7, h: 0.6,
      fontFace: D.h, fontSize: 34, color: D.white, bold: true, margin: 0
    });
    s.addText("A starting point \u2014 adapt with your legal team", {
      x: 0.5, y: 0.95, w: 7, h: 0.35,
      fontFace: D.b, fontSize: 14, color: D.accent, italic: true, margin: 0
    });
    const components = [
      { num: "1", title: "Approved tools list", desc: "Which tools, which tiers. Living document." },
      { num: "2", title: "Data classification", desc: "What can vs cannot go into AI tools." },
      { num: "3", title: "The two-path rule", desc: "General work vs PII-safe setup." },
      { num: "4", title: "Incident reporting", desc: "PII in unapproved tool = potential breach. 72-hour notification." },
      { num: "5", title: "AI literacy training", desc: "EU AI Act Article 4. Legal requirement." },
      { num: "6", title: "Roles & responsibilities", desc: "Who approves, monitors, responds." }
    ];
    const textParts = [];
    components.forEach((c, i) => {
      textParts.push({ text: c.num + "  ", options: { bold: true, color: D.accent, fontSize: 16, fontFace: D.b } });
      textParts.push({ text: c.title, options: { bold: true, color: D.white, fontSize: 15, fontFace: D.b } });
      textParts.push({ text: "  " + c.desc, options: { color: D.muted, fontSize: 13, fontFace: D.b, breakLine: true } });
      if (i < components.length - 1) {
        textParts.push({ text: "", options: { fontSize: 4, breakLine: true } });
      }
    });
    s.addText(textParts, {
      x: 0.7, y: 1.4, w: 8.6, h: 3.9,
      margin: 0, valign: "top"
    });
    s.addNotes("This is a starting point, not an exhaustive policy. Have your legal team review and adapt it. Templates: GDPR Local offers a free AI literacy policy template, FRSecure has an AI acceptable use policy template. The most overlooked component is incident reporting \u2014 employees need to know what to do if they accidentally paste PII into an unapproved tool. Treat it as a potential data breach (72-hour GDPR notification requirement). AI literacy training is enforceable under EU AI Act Article 4 \u2014 not optional. Make it clear: the company is liable (not individual employees), but individuals must follow the policy.");
  }

  // --- Slide 31: Transition to closing ---
  breatherSlide(pres,
    "And remember...",
    "Pause before the closing. The audience has the framework, the comparison, the recommendation, and the policy checklist. Now tie it together."
  );

  // --- Slide 32: Closing part 1 ---
  hero(pres, "The gap between using AI safely\nand using AI recklessly\nisn\u2019t about which model\nis smartest.", {
    size: 40,
    notes: "Let this land. The deck has given the reader everything they need. This closing reframes the entire deck as an empowering choice, not a restrictive burden."
  });

  // --- Slide 33: Closing part 2 ---
  hero(pres, "It\u2019s about which setup\nyou choose \u2014\nand whether you\nchoose at all.", {
    size: 44, color: D.accent,
    notes: "The final line. The audience should leave feeling confident that they can make this decision \u2014 not that they need to hire a compliance consultancy first (though legal review of the final policy is always recommended). Callback to the opening: \u201CJust ChatGPT\u201D and \u201CWild West\u201D both stem from the same gap \u2014 the absence of a deliberate choice."
  });

  // ============================================================
  // WRITE FILE
  // ============================================================
  console.log("Writing presentation...");
  await pres.writeFile({ fileName: path.join(__dirname, "ai-policy.pptx") });
  console.log(`Done! Created ai-policy.pptx (${pres.slides.length} slides, billboard)`);
}

main().catch(err => { console.error("Error:", err); process.exit(1); });
